apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-commit-sync-env
    namespace: github-commit-sync
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:cjyglVzS7ztA7tMH1fa5sEQgMbJsew==,iv:dU7fBdQolqpiy3eN+1uiy1lTMgZY/QCeBhUaO9/M8F8=,tag:Euznf7Y8c4elO/3ze5I3FA==,type:str]
          data:
            GITEA_BASE_URL: ENC[AES256_GCM,data:8MB3rxPv6IMNf2g260Dh2qr4WJ+qdOdGyxHHOxjuL8g=,iv:GdHuIY7Q5vFZBft0HrF7ULMz6HGFLbhJKf7yOyC6F/0=,tag:YXgo3dc12fb9FmlAq4TVrA==,type:str]
            GITEA_TOKEN: ENC[AES256_GCM,data:itIwAlTF2ztKHEQdueMZmdzXiYtgIbFR2CGPOQipGa6vq414fLuydKI81LCo4o4LE56jc0KesnM=,iv:BhOik9imROkd+xkEsmfEwx0pTRJyv+JYquelDX1DyQU=,tag:tWpaFQ/bwUBM0g6G8u1X2g==,type:str]
            GITEA_ACCOUNT: ENC[AES256_GCM,data:TxVfkcOATAM=,iv:3ufEH45347HkDDMLDEcqFJ2zCkOpTC2toEpNWtPBoFc=,tag:42D3MTSD4J/8rsLoTZU9YQ==,type:str]
            GITEA_ACCOUNT_TYPE: ENC[AES256_GCM,data:G7YwA0I/A24=,iv:2a47H8Ysd2MTLBj7v/mY3WCAT1NeR8E/y36cTxlZXqY=,tag:JjXlkVgqGPquojL+bI0ySw==,type:str]
            GITEA_AUTHORS: ENC[AES256_GCM,data:6GSWX7YtYv3hdzH0XDgZoPHO6LguTTUOzDFcmuZWVd2OwZd4PplYbKy4gDs=,iv:oYYSkuQAc7OTIZpnFmDkdMn9cYj78bVEoJyYgKFExyg=,tag:FWbxjMFrXIzGrZYsevUdGA==,type:str]
            GITEA_SKIP_ARCHIVED: ENC[AES256_GCM,data:Ju29Gtgah9Q=,iv:+6OeP5ff/vH+d5mQ2XCHo66x4tbfnX96aoMsj4zntsw=,tag:ikPx4HKnwMMXPfqZ8xugOA==,type:str]
            GITHUB_TOKEN: ENC[AES256_GCM,data:LJaVVhKfq5UuQF3Amd5jZ9fds12KTiEmrVDGrluDhN7dbo+itHq9wPTr3dO8/yofJeXNnOvlP1ioQi174nqgrKS4afyCR98cHRHlTOY+po5vZLFHt+oibBP3Z3yZoTsSKNWfM1XCy08Edgy4DviZ16McW3YAwXCfsmXl7A==,iv:Qy3PoQlfoauz4QVSsHGQdX7tPDFR0sgOTLGzQr9gwaM=,tag:TNnYfwD8FIQ3nLIRBD/Vxw==,type:str]
            GITHUB_REPO: ENC[AES256_GCM,data:mH8oJS9L9EAVP1Pbk0GDGF27zBbbRiVcc5U4sA==,iv:/uVzsHTLSnU7UVHfchyk5cqPW7KiyH+dwuBBl7k7OvA=,tag:B0ZYfjqwxTEh2e1Pnitt3g==,type:str]
            GITHUB_BRANCH: ENC[AES256_GCM,data:G7mNx04sSGM=,iv:Z0Du2wm+hqL1jS1TcW59ksf71VGL/t8QVYa59GkmlWs=,tag:gKKXjeRQv147HwoASohflA==,type:str]
            GITHUB_NAME: ENC[AES256_GCM,data:utPCSt1l2M12Ikss13yP2A0Isq/dSDCsx0pIMZB9YlI=,iv:cf0Un0PecJrZAAOIT/o7gWHwm3r0R4XjQI+hQTX2S7s=,tag:HJzm3hQ0Yb/tk3BKLrgVTA==,type:str]
            GITHUB_EMAIL: ENC[AES256_GCM,data:QGCRrMChDPZBe8rpHFfikEZqafU=,iv:4dNSkm9BbR2NdJ1SCBj3xBhIXrKWsILyjhsRC4h+h+U=,tag:xRNp5fvoeSwaJzLHw1GuzQ==,type:str]
            SYNC_INTERVAL: ENC[AES256_GCM,data:nVnB6w==,iv:5dY5DRUvx1ZDQWb05blCdZ+ZI5pntX4FJ6uJuoPJEKk=,tag:J/9KvSYbfb0xezvonOjpBg==,type:str]
            STARTUP_SYNC: ENC[AES256_GCM,data:DfowvUv2Zr0=,iv:UUVQGhv4m70Hb9dHSbsfr2atueJ5vWvo79dJPZPVi9g=,tag:GjRysd45ZjTPqdgmBfIl6A==,type:str]
            INCLUDE_REPO: ENC[AES256_GCM,data:eQgzwrVaZic=,iv:XSfDaaBxbsAljGTC6XRimLwTEmvyhW3tUrW5Dwxgzdg=,tag:ES5hdiiMTnZheuadmgTjSA==,type:str]
            INCLUDE_MESSAGE: ENC[AES256_GCM,data:/WvPWoUmt60=,iv:3zzD7nEkp9wncOX8U1bL6m5wsV7VnXzhApFay2e3RRc=,tag:+SlAb0/gjhwlrOD6COSvMA==,type:str]
            CONTINUE_ON_REPO_ERROR: ENC[AES256_GCM,data:7+mhdVhFVZs=,iv:6Hdrffrs/wzCo9GCfzWTrgCTYa7F/jsL98dkF7AUGg4=,tag:Fnq5ezqNEH7+B2sBuG35bA==,type:str]
            DRY_RUN: ENC[AES256_GCM,data:G67LwT8oy9w=,iv:pu23ER7hFOPtaRCjvafDu4aDiveLVcCuzh1tYXaPPJo=,tag:t9OtcUTZ8UbhPYIrJlXoBA==,type:str]
            API_TOKEN: ENC[AES256_GCM,data:l8GPg3uBxkqi3rrJdPyJ3EmlrXAE1aMo/nuAasbrGhW3Ojwx4PzMfAnaOrBYxv/2zv5mu6Aokpczt7Mo,iv:yquYYENIxgpZ/DpFqC2+ZRrOttE/T0zM3rn5Niwgfxc=,tag:LfE+Edlyd0zi3oYNwOwxRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QlNZK2hrZGQ4em9IMzFB
            STc3L0FpM2NPMFRUYjMvTkJNNlAxUUlGSkVRCmVlOC9tVFJ5WlFqZWNCQ24yWFpO
            RFV3QWJQd2c3NWxZNVZ3Zm1DRndUbE0KLS0tIEJubnZFT2VCZUxOWlU4bTVGZU4x
            eDhrWEJJZ3N0bGwwVjBNVE1RY0xaTDAKp334XcgQfIvS31h17pUsKaVVJe9xU9BP
            sTyk+RySGGECtY5uF0mvOlKUbEAi8FcBhLqe+2KJomKtYp93AKqgkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T14:01:51Z"
    mac: ENC[AES256_GCM,data:MLi5TzB5GIibJ1ABV5AlxyfbSZ5J6smpe6gBsxi9lhj93syoxlG5a2Az9DQE+O53jnQ+gVKLY6ue12IlXn8dRz/oOeKO+1zpAJs3gYjQ20OvLK4lg82UTD4/lzS2BVdwVwUjJZ43GjIKmCnhp7WFwl9SNyohsGSP1Lx7e97dI4c=,iv:aWRChwaNROLv8jKedpvEB1JERHoKR9L7/DKtqTfNwY0=,tag:9GRgb99NpEfRtDLkUTMAPg==,type:str]
    version: 3.13.3
