apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-commit-sync-env
    namespace: github-commit-sync
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:gd+T1whlvc4/OYKdZ0I1USnKMt7Gm5nngBptTMd31Ks=,iv:My1SBn1fCB/dS/CWP1poK8eds5diCXaNzNrwkW1GxdQ=,tag:QoswzaspvDwFFSbzBzSX2g==,type:str]
          data:
            GITEA_BASE_URL: ENC[AES256_GCM,data:VaG06Uxou6I/nKWvOgtbq4ZGxIEbpabTZw0o7KqIXFY=,iv:njsR1rYQoI/ORqTQfWljzHORj0EjFP41HMGmlSdehbU=,tag:PRUNGrHeU5o19+fXVOCXow==,type:str]
            GITEA_TOKEN: ENC[AES256_GCM,data:j6KHCxFrhzWZ8OL2lFRcG516iM3GhJjjhT01mov8IYoGT2awh0kvRhmRlO1jJwX3QBgklF4dRRQ=,iv:ENPJFlLaleB8uxXUNkgJ/FGMjgLK048VFXK3GNpmLH4=,tag:xM3SgFBs3XMpcpILZGGrzQ==,type:str]
            GITEA_ACCOUNT: ENC[AES256_GCM,data:sE2HbOsUV6k=,iv:njXR7uKwr0MuSFY3H72SNtZIl4CYHSgrlSur40mQp70=,tag:J+M6ae20DChAhAUtEprrtw==,type:str]
            GITEA_ACCOUNT_TYPE: ENC[AES256_GCM,data:JUvoNZzPMYk=,iv:DT3SalMIfc5IxUdiNjWU+7ea0mHVW725xMK2Umb8Tys=,tag:g6Me8/KDMBncVzFMQHZGuw==,type:str]
            GITEA_AUTHORS: ENC[AES256_GCM,data:kd4dfVJxf9u+EPnPMMAQgwB4mYib7SGjIL+CxL1ZRU4tZRJWUmBihHz+ZE8=,iv:78BLhD1y54gkzwxZgevnsKtBhjTS1HGMtHwwbgvTUh8=,tag:XroQbWrmz0ksSMmalwsoCQ==,type:str]
            GITEA_SKIP_ARCHIVED: ENC[AES256_GCM,data:840fJS90NLA=,iv:1HFjbfwWddpoLV22cgvgkgqzpbmi8U04hYWOe6Vuem4=,tag:pf7waZ/Ayps2LM4AEGHsTw==,type:str]
            GITHUB_TOKEN: ENC[AES256_GCM,data:jv0dijtRrzROC5kw3TTNW83fZtgHg6AWkPv60ostoLRCB87dy1P7ptid7j/sbYaQ0BnwLpoO4MwJWc4PNw7h0CVXBGtQzsgm0KfRbarFplYtx3JV/E5w4xJphfYsaXcgXDjMf5dBRwPxwgHMftx/uaK9q1mC+7Gy/S6AOA==,iv:L8PEQi/F8G1Smipf/cb3MkwPNkfY5WGj1h7j1grxbu8=,tag:o2wa2aOyfh5dXzn3/S9zqA==,type:str]
            GITHUB_REPO: ENC[AES256_GCM,data:2zMYLGnWmxBdBX0zkb25gJEgqwe89SVJDYjMbw==,iv:uqQ1w457mZt41vYECIEqVSW2m9Bz6jBqO3j49QgzeeA=,tag:NifFdVBx1Nlp9D3RmDtnsQ==,type:str]
            GITHUB_BRANCH: ENC[AES256_GCM,data:8pNH0WeVxDs=,iv:MoEllURwkV4hNCzDdfN/Qx3NoPtNKbcucIa+PNAb8gg=,tag:icOHuj4Y4M3x/7xisJymBw==,type:str]
            GITHUB_NAME: ENC[AES256_GCM,data:M+SlQT3xa+57RW3QYZz+msBVf8mVYQ4VVT5sNTF8r8o=,iv:14rghfWQZrgfuFZK1FpK0rGech9AbDWL8zJutLpB21U=,tag:oz9phvS794BPgsbguEH31A==,type:str]
            GITHUB_EMAIL: ENC[AES256_GCM,data:eP7uiV2ot/ny4EiPcbzFiFoPTow=,iv:NFgQP1tANSeqJU9LRITWQKwWfamtmQYREkpFptgFJHE=,tag:wuANQyfsH3ZJsgMDA3zpZw==,type:str]
            SYNC_INTERVAL: ENC[AES256_GCM,data:M2og2g==,iv:GulpCQ5KiEIugsTW+tjeDEGRcBXkPiQb0fIAEKbQ9ds=,tag:xyRwBdnOtj6YU7tB4Oq5dw==,type:str]
            STARTUP_SYNC: ENC[AES256_GCM,data:m+NWrNIaE9M=,iv:zKmXRXwpO1/S5EelTixkW5mAlN9u85EhMb4UNu2JdAU=,tag:7E0wC4q5acaDYrX3kt1dmg==,type:str]
            INCLUDE_REPO: ENC[AES256_GCM,data:1QXnpgnDE+I=,iv:FPFJr/xHkJu7KuGBgnVlTo+nIrr0YLiv/dnfkxVGle8=,tag:Yadav/aiIvqg7gZd5qvdwA==,type:str]
            INCLUDE_MESSAGE: ENC[AES256_GCM,data:/Ry1MXzvxaY=,iv:J/tN8MVeBE5v2NGXy0OtgguO7tt2Mfjqo5/r4v4bFJ8=,tag:+dIvgB0gbOv84Owj3NsaPg==,type:str]
            CONTINUE_ON_REPO_ERROR: ENC[AES256_GCM,data:JzrR3opZBOs=,iv:/sDIHfcNz0gr+mwgYmbCrneOHqHy1vsO4ahqVk7akgE=,tag:MEnMMPdXMBBLKgAuAgF4XQ==,type:str]
            DRY_RUN: ENC[AES256_GCM,data:drdnrSl9HYI=,iv:CpbaCpJ1K/ZeCFo+C8fGVfE32+P7MTVCFSAPJtFRdOM=,tag:+C3M1tnFxwBLyYZirxTywA==,type:str]
            API_TOKEN: ENC[AES256_GCM,data:JOWj7i9j5iQf0WMk9PWJYm0nIsPXnS5afnV9E4ayMR8ZHzA1ql34RUMH4xgyzmMfDRQSv0vUC6RsQGng,iv:Y80PPCCyxywHpS2CjJCyuZR7/tFgnJD6QTkdiLTyLYM=,tag:OGu368MjQDlQ9AzComoXkg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeVFKYjREcXB2NTNPS2Jj
            QWYxdWdIVktwL0xkdkp5MEEwL0t5TnVYVXlVClg4M3FWazF6RVplbk5JajZyR2Zs
            bHVrQ2lWeDVWYWhsdDNwM0N4eDBjRmcKLS0tIDI1TEpEY3hwR25VTlc2c1V4MVkw
            NmRrWVFpWUZNMnRPWjdGS0JVOEdIVVEKgvSbc6gIXWg14jSqUk1mdioXZMFCcPyD
            I+0Z9VKOaKrfNnpuQTS2DCUA8jVgokVDonCOj3h8UQ7bstAgj63tPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T13:54:52Z"
    mac: ENC[AES256_GCM,data:g+iqxJqkK6XykfjEpWUcwACzcwLlA4xhTqdD9l8VX66H3E2YN7mievXO44Ogw639JwNxFYN+VIkzqW1nBPwLgCXfcMG+UwJ1TpQXeCc4t7V8i5xAzxxcfOMnMK+gQhVW0rmAodJvQRvfSfQ3XiZqF6EGoXfVwseWfDVV3YCeqSY=,iv:Za+gp7hfGANcoXjJIegsUlPgPeNHuovYsukAeO83Tjk=,tag:famWKcGkf7Ba/8H3kD0/cA==,type:str]
    version: 3.13.3
