apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-commit-sync-env
    namespace: github-commit-sync
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:vUSw64Ra6mCIfFkXU42g/IMNwDxGgg==,iv:pp1ewqnw5AgWPfHfkQi5VNmcLOh7mD5JVpTlyabvrsI=,tag:2MkngfnbqzikdUXA3N9e4A==,type:str]
          data:
            GITEA_BASE_URL: ENC[AES256_GCM,data:hfCGMup+bYylcE6fHz6az6FLmjfOQhA7,iv:eba5wwokqUraXy5uikyfO0qCtih8pXt3ReOdi0kA21k=,tag:TUruXb4Z+BV62MP1gzNbHA==,type:str]
            GITEA_TOKEN: ENC[AES256_GCM,data:KMcaAbU89PwZWWTLPzjaqs19t+SSsqUwDMXcPPtotXx5EjjC5NzHpg==,iv:g5WU6u4HwttBL+2kGRXJOIqUUihtpC8IZTBhqap1ipA=,tag:n0NLi2OMt1AKGC61Hka/fA==,type:str]
            GITEA_ACCOUNT: ENC[AES256_GCM,data:S0OJ0w==,iv:PpjRMbvVsrM4EUzlqec+tu4QX+XptZpB2jfFyrooVxc=,tag:GW+7iymucJTw6oAV05bYgA==,type:str]
            GITEA_ACCOUNT_TYPE: ENC[AES256_GCM,data:GsCkew==,iv:ac/Ez3jWwXLgoUSqIEjkRaCJ9vaDQecnczshSsBebgU=,tag:p+Y8XY78B651mQxMg5GGWw==,type:str]
            GITEA_AUTHORS: ENC[AES256_GCM,data:fGzShn0Mha4NYHVsLOCzboAvi/Jkgjy94CcMRxlp3w==,iv:TLgHEOPyDuYAwo+KuGDlBax4O7SXUTjkrvw2fJOYOa4=,tag:V0tHuQItQ6LXX8bYT3d64A==,type:str]
            GITEA_SKIP_ARCHIVED: ENC[AES256_GCM,data:lsf5Ug==,iv:2KLb2LJ+yz8jriLP+Jgr255VyIh2GTpoV6qjWbSzZHQ=,tag:iOQu8M1THnPnUEDBcdeM5Q==,type:str]
            GITHUB_TOKEN: ENC[AES256_GCM,data:lBXFnIfT3OZcWeIjvSHsB6WGMRJWpTX17GHSMm8lwDDuG53nOb9bxxIQ3cp3rmp5mROEaosAjiZGwMHOGMnytG7rEG5HPj5saCDKOF1teGXHDQwMyavzPSEREbXH,iv:fWVKdp6loUikrjWmXkuvAtWNjjI2I5v7iub0XOVmkUY=,tag:ZSr29+6RwBpBkMfHw4T6cg==,type:str]
            GITHUB_REPO: ENC[AES256_GCM,data:PQX3NQiMuPrMlsulEMT8XLsR8w8K,iv:SgLXpfE4BlBVTSEE30HaBfC3KtuOpsrrY38hd2Ws83E=,tag:w+xjHUXHZ1hwyEv3xZEfTw==,type:str]
            GITHUB_BRANCH: ENC[AES256_GCM,data:fhrEdQ==,iv:RFr0Y8f8eSJ7ZHYxUrAwLMt2JyDsl0e2cOA90c+1AvU=,tag:v5LTcGvr1A4pXBj+QXtX3g==,type:str]
            GITHUB_NAME: ENC[AES256_GCM,data:xle8PHRgvZoikDR+4FBX9WU/nUzAOw==,iv:qIPA9S7LPG1YS7+vP+xJhcLnQi+MBEOG3+omkjJh/Ns=,tag:Kksop76pkFyyG7dQg7JBlg==,type:str]
            GITHUB_EMAIL: ENC[AES256_GCM,data:ivz2P8AKuiBB8DLrLw==,iv:1v7UjkVHVnbu/OTW4RcOEn2NRGFOhqGjn5UC6ePcKBg=,tag:FMqB/7Dhf2D72pyXh39FrQ==,type:str]
            SYNC_INTERVAL: ENC[AES256_GCM,data:Y2U1,iv:AAtGQs3p7N4xBLLrL99mZ/jEOdGyQWu4F43fvuQO15M=,tag:9qJ3OhKV32aXii/6Y+T5eQ==,type:str]
            STARTUP_SYNC: ENC[AES256_GCM,data:FerJXQ==,iv:enSDBrBMHvOKc515WpIs/y4H9YGn7empNb5n1voJ+mE=,tag:vMFYfIZHtLAIly5S2nzZaA==,type:str]
            INCLUDE_REPO: ENC[AES256_GCM,data:svXn+Do=,iv:C2hCWhbLtJdBgVY6mKMsrLse2WrB1k5JX69MMyM8vgU=,tag:HW8T8LyvGsXKwmke7eF8Bg==,type:str]
            INCLUDE_MESSAGE: ENC[AES256_GCM,data:uVgRBGY=,iv:FcuCTsf+BJQpIoQoTdlgmtlsVQnpqkUWgMPN29wmJ1c=,tag:Qa1b1zKUHsh8zDtm7xaqIQ==,type:str]
            CONTINUE_ON_REPO_ERROR: ENC[AES256_GCM,data:KgMsGQ==,iv:AfaD4sY3S9YdizIXctm2gNz/30I3KEyqgabd8aFN5Vs=,tag:UBMA+C64fWMe2f0zOFBtIA==,type:str]
            DRY_RUN: ENC[AES256_GCM,data:SZ2cS2k=,iv:y84ecg0bttJzTWQ+rXW7a+8qdYEjOf1OL7UgnAFuEGI=,tag:oWm39yi1snI9+dFy5cVAnw==,type:str]
            API_TOKEN: ENC[AES256_GCM,data:S0X5qtmsmFiJlLxiJbMYgQLSPhQ3CRSP0S0lyRdh2/JGUfpu8g7/6xxHhw4=,iv:yveKSo/Q5HjP3dmJCsnMK1WTUYYe33W/nWsRYcZ1Nvc=,tag:bYdoqEi5N5DhjizFtkIBmQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMalJjWlcxUzk5NHVDcmNw
            QWZPVThjZDlQcVdRUk0yRUtJV1N2RkVZZmhVCmZrOUNsNWl0Z05icm5DQ096bVNC
            djBnOU5kbnJ4U2dqU2dkTmNZYmlLWmcKLS0tIElSQ01mSGJWWDlvNXhRY3lZU1FN
            NGpKNVJkRFlVMUtwUFdDcDcxK3paVjgKoa+MJKSnBAUFonmkKeOVR3teqNMvb3Zw
            K+JAzxrdUSP/ur9zFv+61O7YY/nm9s7I2RdL4LL1cp9EKtvxpX7iCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T13:35:45Z"
    mac: ENC[AES256_GCM,data:MHF+PtIu+Ds8NbFXsa4eJ38LIncTryEN/O7zb8plZ1pwgbCfvcAXzys8W2M2uv6/bKdQbDsuNjLyIT5iP1H3gii4d8akJF+qZOvalanvuiTUEAuVO35Xsuo5Gddq39byDkurZ/cgDLcVkvz+Fk89fnG06j9slA1Wy3o3viky+88=,iv:s9o1MvlcGhE2ZYPkCbNsgWfBvQ/foXQnqnKA22snd5g=,tag:A1gxDbN870d4Mov8Fa/jUg==,type:str]
    version: 3.13.3
