services:
  minecraft-skyblock-apr2026:
    image: git.radunenu.com/radu/spigotmc-docker:server-latest
    container_name: minecraft-skyblock-apr2026
    pull_policy: always
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - runtime.env
    environment:
      EULA: "true"
    volumes:
      - ${MINECRAFT_DATA_DIR}:/server
    ports:
      - "100.64.0.4:25565:25565/tcp"
      - "100.64.0.4:19132:19132/udp"
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
