apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gitea-runner-mixi-env
    namespace: gitea-runner-mixi
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:98b4PM/2x35bgWdJkmXE4LPXaxYl,iv:cVVi0xooI0gLT41L09V3Nc7i9Gt18CND2TgWvyzNTg4=,tag:6CQQE6yIM+saVUoDSEveww==,type:str]
          stringData:
            GITEA_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:bn8T6Nzk/tuWGQnvN/krzgnYztvQmTLk/LQ0yNnmBEaGlQ4oaypUXw==,iv:FRb5Y6MUqV0mb23qJpz62sDpmy8V6Wz+QECHojRUt58=,tag:UUDGfOY/8Yla4LUXh7srbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRVZ1NEUxSEhOMzJvZnhP
            MmRsQXpMb3BNZy81ZmNwUmFkZzQ3bDRoT3dZCmJ1MDIzdjdXVDNOVlphZUF3OXNE
            Q1JSdVIxWGsremFFV3VzeG5DUXY1K2sKLS0tIDF0MFl0WkZENnJyNUM2U3pBTGtU
            UW5FdisyU2V2OENqbnhSblk0aFVEY2cK0qavgybkbbiqln6RZaKHlu6OsVFPCY5J
            roa4JX9+hjmTd34BKai6dyczmwitTT6aq+PXCrAWI8JVwFzOq06hCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T07:13:58Z"
    mac: ENC[AES256_GCM,data:1vciz+QQUxHyVcys+Si+t0AP+BTlWDk+bPFXtLBaI5DoV+ZgvxTSQzf69MMN3X9GeBVzGhFXAJkTvRVdnEYQvEIa9JL0ztQb7Hw7DlQ0BT28RjjEKdvBFUDm8vZ4PKs6+HHt8PJnDT4fhDBbgBdc7tL4lkFMJ4kbcElsHJyu1ZM=,iv:9fWSZs1L53pTK04l4N847FdKpC8qAw9LNBqIiNTFwc4=,tag:1DCuTXUCosEm43s5NiGJoQ==,type:str]
    version: 3.13.3
