apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gitea-runner-mixi-env
    namespace: gitea-runner-mixi
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:98b4PM/2x35bgWdJkmXE4LPXaxYl,iv:cVVi0xooI0gLT41L09V3Nc7i9Gt18CND2TgWvyzNTg4=,tag:6CQQE6yIM+saVUoDSEveww==,type:str]
          stringData:
            GITEA_RUNNER_REGISTRATION_TOKEN: ENC[AES256_GCM,data:bn8T6Nzk/tuWGQnvN/krzgnYztvQmTLk/LQ0yNnmBEaGlQ4oaypUXw==,iv:FRb5Y6MUqV0mb23qJpz62sDpmy8V6Wz+QECHojRUt58=,tag:UUDGfOY/8Yla4LUXh7srbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcXNlN1h0RDJIZi9mUWJx
            R0NFLzNTS1RIWEtSYk9JQnhVaGtrVjdjNGhJCkdYbmcrQTR2U1VLc3A5QmtJOFk1
            QmE3eU85Yi9UOTRncldrNFd2LzZRcUEKLS0tIDFoKy9XdGJxalpmaVQ5R1E0NVEv
            Q2wzRytmcWRkZDNObUp0L2ttcFVEOEEKny1oId+Nui8WtlNnLeONBmr3V3G8cp5Y
            K7v5/CNoC0rqjlj8PFtLvG0m0RCgBTrwAAKx0yWaLvF1pSOtUiilFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdWV1czZwYUNhNWZubFMx
            REhvN3laTGFheGREajVoQS90SE1TRnBHemhrCktZeHZKOEVUM1lmZkNsQUxoeC9z
            a05wR1MvUldOdVo0V091OHVLRjJSRWMKLS0tIEtjdmpXVUNvU2xLSkdkZEsxZ2FG
            RWlUWmtCd0pObE9pS21KZTJYZjRVUlkK/LGRH8ihg5QtLL3J5FYN24NMK12QJ0JY
            BLHWDeJwr+rOnrFfmOu6vwbNoP/H5FlTZnh66/DdNQIeT0WM79aoaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T07:13:58Z"
    mac: ENC[AES256_GCM,data:1vciz+QQUxHyVcys+Si+t0AP+BTlWDk+bPFXtLBaI5DoV+ZgvxTSQzf69MMN3X9GeBVzGhFXAJkTvRVdnEYQvEIa9JL0ztQb7Hw7DlQ0BT28RjjEKdvBFUDm8vZ4PKs6+HHt8PJnDT4fhDBbgBdc7tL4lkFMJ4kbcElsHJyu1ZM=,iv:9fWSZs1L53pTK04l4N847FdKpC8qAw9LNBqIiNTFwc4=,tag:1DCuTXUCosEm43s5NiGJoQ==,type:str]
    version: 3.13.3
