apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hub-public-db
    namespace: hub
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:+FJJI6wP1ymjM9657A==,iv:HE3OSWY8qa/HlKOPgU6yOXaTBhTYRAvoyyRVAs0D1g8=,tag:PBAZTFa2DVq00YvRkRvoOA==,type:str]
          type: ENC[AES256_GCM,data:c8Zu5PUVMwXCGwzOikjUp9W36zs+1mCp,iv:n+NWrXIAQke4JqRyMi/+uoiHV0LZOrSjd/Syq6GLq6Y=,tag:K6lDVyx57nGryNq9sqWHbQ==,type:str]
          stringData:
            username: ENC[AES256_GCM,data:64rfQtovNg8Xew==,iv:VdPlfVRyyzw+CqC24DAYt+junlUAtarEg28mB/+xffA=,tag:Cutei6S9V2Q//LRhDbCotw==,type:str]
            password: ENC[AES256_GCM,data:mqNgnlUnrWgjHIVw6e67TiKHP9/MSx+3iP/uYZpKUBM=,iv:CYY3jk8qEGXjElnLan9hdFhvVkIsJJI0XKKFKSNYY9A=,tag:HnFRYXQF3bj8/mrgtZXe2Q==,type:str]
            uri: ENC[AES256_GCM,data:L4FSTHE6L142ANZ8K9bpxoLrvzyq5xGemIhKsex9DTaekCAXY6Vv2Ue/s2pr2HI6U/TVMokSa6EOZlU1qZIjJ+EbTFqH4CtFrg7Hy1cc1VD9ASk=,iv:iDhqpXt3XYgkzBcEccw/rgtWq3CFei9hToDXyuJVKoc=,tag:PE4p2CWQVOuFIibVCAEp2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTUY1UEZyQkZBWE10M2Vy
            K3dZTTVOSjQ1Mi9iU1lnTmU5UzdVbkFQVDFnCjIwNWhaY2FQdkRVdU15SkM0M1VG
            cnh0czBSRWN0UUdPZGx5Yml5bk9pV2cKLS0tIE1SM2xUQlNWQjJ5Y0kyVDdhejlj
            MC9HUUNjV2U4OWVJZGIzUndZVS80dGcK+qCsSwVYl1noebH8Bi3SgbvLOsuscRPi
            1hY1ZwshBN/PHbikZZ+tvonk9QWh5O8B0nczhJW08d3QGDRkA0jLEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVUQycEZYVTBIWUlxV2lo
            eC8zbUMvNXBPd0NHcVl2bjRRVkxsdldDVXc4ClRPN3kvZG5BYTRuS3BzaXErSWFI
            SUlodUVyR0poRFhpRGM0bmdGNHRvQVEKLS0tIHZPYlZLc2wvd0FPMHJZMTl3T1E3
            cFI0WGpDNDBmM3U0bHRHUEpRTkkzSVEKbxVUcXqVqivJJDXOw5xCk2MKnZofdZj1
            UsePzuOnRUI9fd7e5FAuV2TdTINdH99lCwQsTFYBNZU2Z4kYN2+PQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-10-07T23:52:22Z"
    mac: ENC[AES256_GCM,data:RrRQgnnHWYtIpcHJultXbH1blFJD28VOOCmZsQbf5eJj5TaVSvIw19WZDpB4bW5Szbzxz13jRkVfVfXmiolFL7NzRyHKwyzw/xn4SHDNB5GqypBYZYNzN87NXRtOnrweuVKkUvfEOVgZvgLSzf5XfsJjfyJn0PqvsqIuvjtCU1c=,iv:10kd3YDPn7RmySgGCqHb6LcH1t4bwwOrWXJmHSGEnlY=,tag:I+hVl5+NxLThaamFTNgtNA==,type:str]
    version: 3.13.3
