# -------------------------
# Server Connection
# -------------------------

serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}

# -------------------------
# Authentication
# -------------------------

{{- if .Envs.FRP_TOKEN }}
auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"
{{- end }}

# -------------------------
# TLS Settings
# -------------------------

transport.tls.enable = {{ .Envs.FRP_TLS_ENABLE }}

# -------------------------
# Logging
# -------------------------

log.to = "console"
log.level = "{{ .Envs.FRP_LOG_LEVEL }}"
{{- if .Envs.FRP_LOG_MAX_DAYS }}
log.maxDays = {{ .Envs.FRP_LOG_MAX_DAYS }}
{{- end }}

# -------------------------
# HTTP Proxy
# -------------------------

[[proxies]]
name = "{{ .Envs.FRP_PROXY_NAME }}"
type = "http"

# Local service target
localIP = "{{ .Envs.FRP_LOCAL_IP }}"
localPort = {{ .Envs.FRP_LOCAL_PORT }}

# Domain exposed by FRPS
customDomains = ["{{ .Envs.FRP_DOMAIN }}"]

{{- if .Envs.FRP_PROXY_PROTOCOL_VERSION }}
# Forward IPs of clients
transport.proxyProtocolVersion = "{{ .Envs.FRP_PROXY_PROTOCOL_VERSION }}"
{{- end }}
