# -------------------------
# Server connection
# -------------------------

serverAddr = "{{ .Envs.FRP_SERVER_ADDR }}"
serverPort = {{ .Envs.FRP_SERVER_PORT }}

# -------------------------
# Authentication
# -------------------------

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

# -------------------------
# TLS
# -------------------------

transport.tls.enable = {{ .Envs.FRP_TLS_ENABLE }}

# -------------------------
# Logging
# -------------------------

log.to = "console"
log.level = "{{ .Envs.FRP_LOG_LEVEL }}"

# -------------------------
# TCP proxy
# -------------------------

[[proxies]]
name = "{{ .Envs.FRP_PROXY_NAME }}"
type = "tcp"

localIP = "{{ .Envs.FRP_LOCAL_IP }}"
localPort = {{ .Envs.FRP_LOCAL_PORT }}

remotePort = {{ .Envs.FRP_REMOTE_PORT }}

transport.useEncryption = {{ .Envs.FRP_USE_ENCRYPTION }}
transport.useCompression = {{ .Envs.FRP_USE_COMPRESSION }}

# Forward connection IP
transport.proxyProtocolVersion = "v2"
