apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      dashboard: true

    ingressRoute:
      dashboard:
        enabled: true
        entryPoints:
          - traefik

    metrics:
      prometheus:
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: true
        service:
          enabled: true
          annotations:
            monitoring.radunenu.com/scrape: "true"
            monitoring.radunenu.com/path: /metrics
