apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minecraft-hc-env
    namespace: minecraft-hc
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:aSyu5NZmfpspfs8mMRHAHg==,iv:67RgLoG1UCaAD/R/nmq3lZ5pmEjJQ4V5uDMJ26TbXdA=,tag:bWylQSBxrHyLff5ku2vD4g==,type:str]
          stringData:
            MINECRAFT_DATA_DIR: ENC[AES256_GCM,data:YNk2L/4xILLjO411vBU3aPIoY0kyrfRQCQhHUlUN3Bto1FO/npbgM+V1cRBAWmM=,iv:Kfmxk+Z3A3yRC25BP7UwxCXh5j0ihQVKmXpp4FS47kI=,tag:NYbsN23+L3EMWj34RhKp5A==,type:str]
            HARDCORE: ENC[AES256_GCM,data:HLl4mi4=,iv:Apjv3Ctp8O95HimdOjPELSBzAITOVpIy7XdfV0aiUkQ=,tag:iQ3ocUi9jvXd7oN27/1A+g==,type:str]
            WHITE_LIST: ENC[AES256_GCM,data:DI+/CA==,iv:fJUYgZUuGo8ZHipBnQV5+u8Hpc2ibbr3bIYrDjHu9Uw=,tag:E8aoTc2oIBOE9Y1UGojKLQ==,type:str]
            MC_VERSION: ENC[AES256_GCM,data:5biYwQ==,iv:tdGUiNx3W3F8dISwFDVMG9zok+vl1Ma5QPRegTv26Qs=,tag:T709mzE+nfU/FC4SNPwkNQ==,type:str]
            JVM_MIN_RAM: ENC[AES256_GCM,data:vSQ=,iv:4842Fg8Zq5m9C1Zu2ebi6d1mdYjuBR3snq/mCa9m3Kc=,tag:405AzDz/6n5f8ZRVP4W42w==,type:str]
            JVM_MAX_RAM: ENC[AES256_GCM,data:9LU=,iv:CehF6Tg7uk/vcSNJy48vAh26rMBbesamYD60PUUO6+I=,tag:JmxzECr494djyzs+Z9ezkA==,type:str]
            MOTD: ENC[AES256_GCM,data:j5e32Q2iSzN+5vLiZop4J8yGsmJ6SQK6DNB6m1c6Rzd6,iv:7lvAGXUws25llY89i+0HmVj224y7QZLUL+0jH7+Ezy0=,tag:w5bFIDujYMEF2gGU0Z3dSQ==,type:str]
            SERVER_PORT: ENC[AES256_GCM,data:Wz0QpLQ=,iv:IHNLr2Vd5peWLQ/51JYUs9LS0fAw4+GunGDyeIoDsE4=,tag:J2BhXkLVuKNICW4y+ffxnA==,type:str]
            SFTP_USERNAME: ENC[AES256_GCM,data:gj0iYB2KFQ==,iv:eGK8OGIY1xV01qb2l4jtSAV46QR1OeVWn2KAGooBhh4=,tag:hlWDrgFBRSqc8f6b7n+fow==,type:str]
            SFTP_PASSWORD: ENC[AES256_GCM,data:pyuvcM6IJZ/vINc6CtKcwlF45g==,iv:iaOLc7uhHOGaxq+1nH/M+k/DzRKF5wRqN7KQvyL1NZs=,tag:I8byAvtnCubijy8xbeDaQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeTZoQlh0V01pWlFtU3Fi
            VjFaVDdhWVQvRUt6YkF6cVJWUXJJNWR3akdZClRTVmV4TkZ2bE1RVlZtU3Q2Y0NS
            eTRVdWZUazRjSXR0VDhBOUdja2FZcjgKLS0tIEJ1ZkpCUEswaWZNaDhJYWU4TkZG
            TGpadGFBanR0eENVYXNaZ1FCcy9rZlkKKG/pNFqgGAtq8svI5JALYhXx84+CcgQe
            LfnteYvnKuCJCo+kvxNKoOlEvB0Z6+ivnD6QyPMQXxD6IpVkSEshzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-24T06:27:33Z"
    mac: ENC[AES256_GCM,data:Y5aXbhA7LUyMZnTvXUB7roAQ2gExi/iJtD4TbySuaRE9FwPzSfF+YTik7nSJkBQlD216Z8/sNBIJJ4sy8EVNcXoIxYjV1wKIv7La5dJrxqHcwQWP5mwxU3/6rVB2PfADvqb6oLoliQZ62uESZjLCABbCH4dsMAduEHgWUw8/uRY=,iv:7Uo8At+U/PPO4gkrZiSq/T/uVpSuGbzsfP/dRBU4P9c=,tag:+52V0HVaSCGNVaSvF22RGQ==,type:str]
    version: 3.13.3
