apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minecraft-hc-env
    namespace: minecraft-hc
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:aSyu5NZmfpspfs8mMRHAHg==,iv:67RgLoG1UCaAD/R/nmq3lZ5pmEjJQ4V5uDMJ26TbXdA=,tag:bWylQSBxrHyLff5ku2vD4g==,type:str]
          stringData:
            MINECRAFT_DATA_DIR: ENC[AES256_GCM,data:YNk2L/4xILLjO411vBU3aPIoY0kyrfRQCQhHUlUN3Bto1FO/npbgM+V1cRBAWmM=,iv:Kfmxk+Z3A3yRC25BP7UwxCXh5j0ihQVKmXpp4FS47kI=,tag:NYbsN23+L3EMWj34RhKp5A==,type:str]
            HARDCORE: ENC[AES256_GCM,data:HLl4mi4=,iv:Apjv3Ctp8O95HimdOjPELSBzAITOVpIy7XdfV0aiUkQ=,tag:iQ3ocUi9jvXd7oN27/1A+g==,type:str]
            WHITE_LIST: ENC[AES256_GCM,data:DI+/CA==,iv:fJUYgZUuGo8ZHipBnQV5+u8Hpc2ibbr3bIYrDjHu9Uw=,tag:E8aoTc2oIBOE9Y1UGojKLQ==,type:str]
            MC_VERSION: ENC[AES256_GCM,data:5biYwQ==,iv:tdGUiNx3W3F8dISwFDVMG9zok+vl1Ma5QPRegTv26Qs=,tag:T709mzE+nfU/FC4SNPwkNQ==,type:str]
            JVM_MIN_RAM: ENC[AES256_GCM,data:vSQ=,iv:4842Fg8Zq5m9C1Zu2ebi6d1mdYjuBR3snq/mCa9m3Kc=,tag:405AzDz/6n5f8ZRVP4W42w==,type:str]
            JVM_MAX_RAM: ENC[AES256_GCM,data:9LU=,iv:CehF6Tg7uk/vcSNJy48vAh26rMBbesamYD60PUUO6+I=,tag:JmxzECr494djyzs+Z9ezkA==,type:str]
            MOTD: ENC[AES256_GCM,data:j5e32Q2iSzN+5vLiZop4J8yGsmJ6SQK6DNB6m1c6Rzd6,iv:7lvAGXUws25llY89i+0HmVj224y7QZLUL+0jH7+Ezy0=,tag:w5bFIDujYMEF2gGU0Z3dSQ==,type:str]
            SERVER_PORT: ENC[AES256_GCM,data:Wz0QpLQ=,iv:IHNLr2Vd5peWLQ/51JYUs9LS0fAw4+GunGDyeIoDsE4=,tag:J2BhXkLVuKNICW4y+ffxnA==,type:str]
            FRP_SERVER_ADDR: ENC[AES256_GCM,data:eN9sI641Tt16D+Kzew==,iv:V+NAdc9MtnZn+TFNJ0SfxvZxNvZTFn2meTCWFutZxG0=,tag:pp8McXdpQgKPcvCfRJhrlQ==,type:str]
            FRP_SERVER_PORT: ENC[AES256_GCM,data:PxYSf4k=,iv:mpELrhEbu69CmNxNkNEcY1j0F2NqgaegUe1p1S6ohdE=,tag:bxAA2eYtCkTHaJT1lS64Jw==,type:str]
            FRP_TOKEN: ENC[AES256_GCM,data:3cahUH7q6cD7e0N8OV41X3ufIqsG2YdaIlgdr/aguEyUfxXRl/OqSrYC7KeT8Gtx,iv:PgdGXHSIXR/fqwGKqtDulv3ObBLSkc8+ikevOW211OA=,tag:APLMx4jt7cORcZGoxDhz/g==,type:str]
            FRP_PROXY_NAME: ENC[AES256_GCM,data:Sa5pIMeV89aYbesuuXOB3dBBpCAFYngfmIWAkw==,iv:+bORiPAEGaMt7cY6iEYJfTBORgqsBU5fm24VQd2niwk=,tag:XacJRNeGtDls8yAImRzUIg==,type:str]
            FRP_LOCAL_IP: ENC[AES256_GCM,data:bkR7ZSH2Zd9TTUGzZKQ7JUxY56PHbcA=,iv:Hz9VKZUC9mvouwQvEusRrlSa4ssn6Xv5ez+TT1vRsik=,tag:EfHFNR7h06PHTXExQLMVsw==,type:str]
            FRP_LOCAL_PORT: ENC[AES256_GCM,data:1lMUOCo=,iv:7ecvu6FoIkcNGftHV0ijGsrypWqnBLF3LFtLjlkU31c=,tag:z8nX/Wc+aUxVYXY4q8ZW5w==,type:str]
            FRP_REMOTE_PORT: ENC[AES256_GCM,data:r2raLg==,iv:uRbTHYmXK3a5Q17blBaqqhMdQa8Rb4+HtqZjmmICPG0=,tag:wri7p7MD8yN7HjjVtf0YeQ==,type:str]
            FRP_TLS_ENABLE: ENC[AES256_GCM,data:RAUhYQ==,iv:Q6xkbx2K/07jniBFowmeJTjJn5JVlN2D9LyMc92K0bg=,tag:Ks41bSJ9dO1VHgkEJXU+kA==,type:str]
            FRP_LOG_LEVEL: ENC[AES256_GCM,data:YaQPOQ==,iv:dy27SMT+/KEZMejRl7tTrBmajVbzJSF+gtDzZPC3Pws=,tag:e8tGKXan0BQ3shQkwtNmJA==,type:str]
            SFTP_USERNAME: ENC[AES256_GCM,data:pbi5eCD5ww==,iv:DUoavGzjv+C7ZHJOKNwUqZ42Iudv2aD94qn1BhvO3sc=,tag:UvrczH5n+AUEycjW4gkwPw==,type:str]
            SFTP_PASSWORD: ENC[AES256_GCM,data:tqVtlzPPPerVINnlNasNQSniTbSuiI0QAGf1B4sNNFA=,iv:/RHb9MGKW7LtNIsDgFeDFkE7sMk1rx4ahhiRDkTHtpk=,tag:g22wNYYCYicLBDfz1iVs7g==,type:str]
            FRP_SFTP_PROXY_NAME: ENC[AES256_GCM,data:rlLrXriZuKoHFFsJ9f/fR19B8Tm+Q7XGMoOjwQ==,iv:hkFs00tmYBhqz2AQqGuf4VhcLg37jC71jIjcPJMrY7k=,tag:yMQ5lwDjswqUvvG8MEbURQ==,type:str]
            FRP_SFTP_LOCAL_IP: ENC[AES256_GCM,data:zwoWnw==,iv:bALz5PzN6KQ8UdjxPBetkQ7poJB5sD2gBY1rFZAg2lA=,tag:m3D7TAo44cALQQUsjp+z5w==,type:str]
            FRP_SFTP_LOCAL_PORT: ENC[AES256_GCM,data:TEU=,iv:9eD3Bl/E0c9H3AnyRdkH7niAyRsx/cLRsLGmlQY+HjQ=,tag:KhzOFqhk45lp/7oSsf0OXA==,type:str]
            FRP_SFTP_REMOTE_PORT: ENC[AES256_GCM,data:zKkN6kE=,iv:7NcdIP4CeFPAKadfeJv2ReUOJBicJGW5nuKemqDeSbE=,tag:ubKlcUatxJXoQFtCDW64Lw==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeTZoQlh0V01pWlFtU3Fi
            VjFaVDdhWVQvRUt6YkF6cVJWUXJJNWR3akdZClRTVmV4TkZ2bE1RVlZtU3Q2Y0NS
            eTRVdWZUazRjSXR0VDhBOUdja2FZcjgKLS0tIEJ1ZkpCUEswaWZNaDhJYWU4TkZG
            TGpadGFBanR0eENVYXNaZ1FCcy9rZlkKKG/pNFqgGAtq8svI5JALYhXx84+CcgQe
            LfnteYvnKuCJCo+kvxNKoOlEvB0Z6+ivnD6QyPMQXxD6IpVkSEshzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T20:03:24Z"
    mac: ENC[AES256_GCM,data:6gKWcGHQMxqSe9UpYGFxXdkvfk0yMcloM/0zqAYt3pLKOIEOmpgNMeFg6Uh5oVodUEvlKlueFPnqxwjJ7vVKDD3f7tArPHK8tB2Voi2FzCAFwKSCCO5cV0AboE7J+/YprCHLZ9HdJMu2dNtklra2HmW+qiF7G427U3zlmDzfsDc=,iv:t9eZPZjCnoOharTUrlGJJ1fqzHl+dD/HQyUToW7aghQ=,tag:o+p9n5wnY8A0ngJGLm3ykQ==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
