apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: sops-test
    namespace: element-call
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:cgJ0Bn1FLb4V,iv:CP7lPd4q0RI9XkIRfxILTqMvh+gqk9uwpQJuMPDaLzw=,tag:wsPEFvY7Q9EaSO1/7j+8Og==,type:str]
          stringData:
            TEST_VALUE: ENC[AES256_GCM,data:Ca+6Wg+Una5KY/p/tdZoqPf3/EP69SA=,iv:er84r4nX4R0UVngPMq+pirZ4B2CvhAGXrFiw0MwN/Os=,tag:u4HAHoGS6Yf5AZNWDIjO/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQlB6Q0lkaGFGV2U4UitE
            ZU9DbUxkUVl5UlowTUFwbUFnNUpyek1oUVJJClo0YXZIeVJncW4vYXg4WVIrdFhx
            ejBLY0ZZTEJOTVR0djcyTG9IRFFoUEkKLS0tIFVnWXRhWkorc1JmYjAwMGM4NS8v
            bkRkSGtzMk5OanVJN09JWDh4MjJwQVEKXJMKAidGrvWZlTbiPdyD35n9IMxhxdVo
            yCZSxtyFB80grGYHPYj8QeIXZ5CIYtAsyGW8ywvOf4oBIMXReNFG/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-14T07:53:04Z"
    mac: ENC[AES256_GCM,data:Vr8r7I9GzHv6XF46Az5OSbFFQ+B6vyNV1kMQRJw04cDTf5aiqCYw56Gf1O2gM1KQvtZSRHuNvbufdFeXD+mE/LR6LIsBnM70YfzKJYu+aKmThULQutyMOotuDlH6eTFmwHSR/wH823gDslX9m+996eSBywpt/+PhAnp1g9BvTcI=,iv:b25AM4a2+ssLeDhhVhcfA7QBilyGpu4+sDN+vzbGib8=,tag:L4zd3HIiHRWtmMQH37cNgA==,type:str]
    version: 3.13.3
