apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: send-oauth2
    namespace: send
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Xgi4T8kKx1A/b/E=,iv:2k50AIWNrcmymHcKGe9CybaPocC9oxzHgGgGZHd5cmI=,tag:TQZAJbN0MKbuCXV8GDatpw==,type:str]
          stringData:
            OAUTH2_PROXY_OIDC_ISSUER_URL: ENC[AES256_GCM,data:rBgKXXWTXuzpaSWxhtGwYXR5zJlYA0n/nOw4W8MCZCnjcmjusA==,iv:VDbl4zg/7tQPTsTWbCCT2iXLO3vOAxfIIpxc9lPGOBE=,tag:BJNbWV2olVwxOntJ+p0DUA==,type:str]
            OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:Le1lx8j3XEMDBiF8aPxaElfl6Q5LVl3l/13CyeaQycY=,iv:ZTRPjmIb/GSOD1YVQl0ksrFHD5MNb1UN1h7VBzOMUb4=,tag:57PEuCRMH6sfoEkVxYPb7A==,type:str]
            OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:0c/JXyNxJ5OzjK0ksfNA/UE1USSRYAak58oBAQxsTqtnkpzBxXo01gWIig==,iv:3kqNw4J8v6xo19wrVw8BpYSscI2Hsmda9Cj3w3wPj0M=,tag:TiI+rGh88S7pZga7r4ZQ8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bDlmTWhLZ0crTGJJbGVM
            WVY3Zk50dTVsM0xoR1JhOVBaYmRtSXZVQUZBCnBtZTF4M3NvdVNZdWxyaUVoNkxh
            aWl3NHVhNGM4UFVmQk9RY1RDWnlaU0UKLS0tIDhFSWExTGhqWmtzUGttdHZKS05w
            ang3WUxvcW1DVW5RTHZrY0NHUDdkbGMKC7DHvUftzaPIGSmziQNg6H21VkboeSEV
            boWSfb5qg5L6XEz29guH6I7JFqH3D5jbysN6OctrI2JDgWxapjd4pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-30T09:28:35Z"
    mac: ENC[AES256_GCM,data:u9oKZG9Q80xOjOgT2TQw6xPYgmGn01iP/h22NSMdrBAT9YA64DJAkLBa6lv/aSJlZtQfBW4BeU8kcv+4y4dXM8lyuCObidlnxGrRIGh96VbL9FTGE0bftR1iVUFqmnJbwkY/IQBHyM1hbvWt/PxByAtyZ9LkbwES7JYUR2stOcE=,iv:pF52V/EAEMmqwzo72hkQcOvGqvFUx/pELHvXd6x9+dQ=,tag:pIUEhcwJh9kG9dPTQohurQ==,type:str]
    version: 3.13.3
