apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pinga-env
    namespace: pinga
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:1TiFgAsYzO7I,iv:qYVCE0kbsVtlGbbGBPxB2N8BsuMXKyK1XGNguKrQcCU=,tag:0SCWk60WbCgVkHM9cwV4NQ==,type:str]
          stringData:
            PINGA_BOOTSTRAP_SECRET: ENC[AES256_GCM,data:NCaxVDp1FaCzL3U40m6r53K47eBmqBh2dFKVl85mKwRbnsLSIAExDIHqEkPVtC0z4c1ADX1kxAvyjgncfgtmrA==,iv:mqQSpE4lhx5fDxZ1m0X98vzzWq3ALh+koFfhNUqKe0c=,tag:wJjdb1nTwUFrlmmnhOy56Q==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWXQyWFlVYldmcWkzRUEw
            YTZDREhYODIycHZmUm50L1VyYTc2NHNUZnpBClA1N2Mvd1U4UzBnaTB1SVVpQTRF
            My9uVFNuSTZDRklsWkJ0M0t6UlBERDAKLS0tIFlwQmxhTGl5cVFoS1lhOGltWVlP
            ZUdHWUd6bG5Ra0lQU1JNVlZybVZZa1kK9dh6q8WNYfiGw1t8mTUWLXQiSQDI/dCb
            a1EI7oJOcH4WLPdh3jvUK+ymtttfJ6UwSHXK/gNDo0rN1KeyrFgrZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T13:30:41Z"
    mac: ENC[AES256_GCM,data:UGahFNA3yu73EjExlmvA9NUbYjRzrrBi715htWqvW4HLgI/VGw+IHmhZ1/zvXaM8zjOCWUkDBs//uxqUK7Uojviy3THk2O0ZAq6KRiBb7hLb45FGQOpKPR8xzCwAAQP3Mt3u4pkjwh8eDh9XvOUMLVQ/TKkjQUlglE/DCoOrEJQ=,iv:UFIjglevWn9TM4JoCEOCaS0CQTWpeqpe+mzG/4nA+3g=,tag:ot5GbAgTgzrL1bsqdBI5YQ==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
