{
	"data": "ENC[AES256_GCM,data:4I/CptEtC9eRDwuvJA3L8TNIEDWv+PmH7DQPZyPOP6XTkylGQ3OlvMVEMnZ8vGuI5TjKR93UMF2a6uN8DE9OkfDdeqkTrt5f1Tg6t7LktRmvVdCdN8iIQ7VxOPFTBESBWvXk1SYaRvU3GLj4xh8VTnO39bK1DjTtWHcOwRJVAjmQ/zT5oGsUKtTklVmdu1tlZu4+4xTM1Wf+2w==,iv:YfUw2so6HS7fB3JPq595QZR5IWSVl8ET+/RMwqiT2Ec=,tag:jebqQVxV0+ttZQJDmrTWKQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age12kcxltjmxtsc57vhq0tfyyw9xq0qgfqpqygnffjfa8s25nxasasq4wspf4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOTFYb1d1Y3RpT3U4Mllo\nUXd4d0xEZ2FOdkhWd21wMkhkc3BrYWx5WFhVCjR2NUdFU1pOKzBsQlltZElRRnBa\ncitFT2FRRjFxTHRTa3d5dGxzNWZrMWsKLS0tIERvOG44Vm94YVlqR3I1TDlCbDdO\nb1ZhY2tvZTFQT0R1cmpIV0x6akFTWTAK2PZKQUF2TEIUX0hmKf0drDX4heGgxzpR\nMD3YfYAsUyc1OlEAXp51+l88VFkjN4lmIQJP+dRM189Do9gEFmZoTA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-15T15:35:38Z",
		"mac": "ENC[AES256_GCM,data:+ebFt1R3Q3ekSjOsWdOM6E8X5Ysp9QdjZXhWXoJTz0Kymw/z3aWSGBIbSi9YydJ4T/c2mK6A0MygHFi4G0KVSjGE2FpEP5dP7mwoHgyyiSEo4lM+upFQdoTyYd9d56v7N0Z4TRPkknxi9JhQnZGx19NYhcXbx2cbiOkVPiKTmGM=,iv:24Irr4dn0+kv42mqbhJVEr5/dLwILEHoHuYiJM69vt4=,tag:K9eu0OJ6H4ornxGG92WnFQ==,type:str]",
		"version": "3.12.1"
	}
}
