{
	"data": "ENC[AES256_GCM,data:M+hKmmnX0sPXjH2pLFb+p+sLuMweLxNH1UM3QYed5zH/klNc4FxtSEQYA5fqDl3cgtftRMC7f/iEa1evo3JKJHlOFLp+F6zBtvNbBw8lT7eorC4N03xl/hUuABcgQ0KstNzRuHgZ9M5INkiIPZR+tJtDNZ2EYbsvsZaZMC7HG6NXcFBtz/goGzxflybkWyXINt87d4618cNXcA==,iv:pppR2nCyDdxCHTfmq0euF37+drpPVTrfZ/Yl58N4lQc=,tag:LdJeQD+qkcp9GmDz/WuM4g==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age12kcxltjmxtsc57vhq0tfyyw9xq0qgfqpqygnffjfa8s25nxasasq4wspf4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OFRWNzdqV2NjTkRjeEdp\nUmU1UG4vNlppUlBBa0xPTVZ2a1AwOTdjQ2lnCmxzdWxPTUVRREVGdHZEYTR3SnEx\nblI2YjcrQXRUN1crOFcxb3QyZ1pjRUkKLS0tIHQxeWtBcmZnRXh4N2RIUStsTndY\nbzUrZzNPMXJLVVJsNHMvWVVoazlRa3cKKg9m23kf/Tyjeau8D+un2UaeTUv0JWYU\nCTar0ii5TelgRUy+2cVc5EF+UjgOgglfyYRRwhEu0EnG2gwrs9+5wQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-14T13:53:40Z",
		"mac": "ENC[AES256_GCM,data:1BdeTwY+lYUaKhr1CotGpT2CtE13wl9ADusmArQ4BUeBmHt7c3tvRTFtVsQDDmCRBcoGH8aQyhD8NcUHlJ2YjQ5Od7Ix89td6HuF7CW3QRSAUfETUaMcz3jSjzE2WUlFzEenjXG8Gm0ytkKYWE4D8K4IPbTgHKlR8h3NLU9hYgU=,iv:Ke06gm8waz66T4ylJNtp6g4QEC4X1/d59LXWONkHWIw=,tag:yfHS8HmzpF6D5LEAZW1YUA==,type:str]",
		"version": "3.12.1"
	}
}
