{
	"data": "ENC[AES256_GCM,data:NYR7qVZAOxpvGvCX1oIAqghrZdH23Du00AVOCy1TOVAP1pC4lMCPwXIWkvhW8h6R8Yx+pu2CXNks0GFvm0d1Hcm0iW9K+hDYPqyr8RPqU8PXwuL+CvsFX/ZgB3CdTFqRE7KHr9CIO5F142CNK+17nTk/BYmiqvuC3ccZH32jXfLrwxoknqHEjjniDxTulTZLn5VL11JjWfcqdA==,iv:F8QzdhCocPcDkdj5S9sJZ62Vcb2n0n61Q8V41BcSH7o=,tag:kqzRd2O0I89fxHB2xe1cLA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age12kcxltjmxtsc57vhq0tfyyw9xq0qgfqpqygnffjfa8s25nxasasq4wspf4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4V3lQUXovelNYbExodmFT\nb1NWeVNBWlpkV0lEWVg2eVdVejcvYXhhZGxZCmdwVS82ZzIzdjhveXluRFRWeE5F\nVlk1cHBDSFIycDhFLythdzdCQUxabTAKLS0tIGVXTjhtMU40b3U0cStONEdTVUFE\nVlpJMVJRc3MvbVN6a094OXpRUERLQW8KeVvNL7u3FfvraFn1u8cxjOJgw5bNwTRa\nIKcwvm182wWz1ZSH6McLKv/l6LpANYLkiZDZ8BXBvbysYX5oofTVRg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-15T16:28:52Z",
		"mac": "ENC[AES256_GCM,data:q//2ob2lIGRTbpfPBRlZoYzyCX0jNrMGM/mDEAsDZAJn+BDl+pjaYQX+MkVywrlBLpGdEftN3n9THs24WqRVSjotWAgt0wX/9nIasnWJuYL0hYtyDwvylF4qpGf+oPSTfcur1lwIhIteTaxsbPzTcJM+vBNZ/acQitNKO4eXrB4=,iv:BC+GNgWbC4O7Tf1+aFrKDM4dL3T4t5vBdyrkP+WJgok=,tag:yzV54PYCI8pbC/3fev3hxA==,type:str]",
		"version": "3.12.1"
	}
}
