apiVersion: v1
kind: ConfigMap
metadata:
  name: headscale-config
  namespace: headscale
data:
  config.yaml: |
    server_url: https://hs.radunenu.com
    listen_addr: 0.0.0.0:8080
    metrics_listen_addr: 0.0.0.0:9090

    database:
      type: sqlite
      sqlite:
        path: /var/lib/headscale/db.sqlite

    tls_cert_path: ""
    tls_key_path: ""
