apiVersion: apps/v1
kind: Deployment
metadata:
  name: headscale
  namespace: headscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headscale
  template:
    metadata:
      labels:
        app: headscale
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
        - name: headscale
          image: ghcr.io/juanfont/headscale:v0.29.3
          args:
            - serve
          ports:
            - containerPort: 8080
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/headscale
              readOnly: true
            - name: data
              mountPath: /var/lib/headscale

      volumes:
        - name: config
          configMap:
            name: headscale-config
        - name: data
          persistentVolumeClaim:
            claimName: headscale-data
