apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: rybbit-env
    namespace: rybbit
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:4rUN8bN86omyzA==,iv:mqTs3n+68UKgq2EybVA8wm8Uc/NrKZdrSOEzOED9BC4=,tag:eJN9tB5IO813/qRPKdgy0w==,type:str]
          data:
            POSTGRES_DB: ENC[AES256_GCM,data:4FcpbTKFDF6xdmQs,iv:rNXfH2AAgCh4fC1Zg+2nqJbsqcxZI1qFJ26LcVA6lII=,tag:jItc3WjMnJFteYkMbvWqdQ==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:NOQ+mjR069k=,iv:ECgTkDLDi6kynRaqik9NKMGJga6klZfMrLuuM//AhVg=,tag:1UkvbDnv/TJ+DBLf/wR1og==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:M4lS6fiMsxit8uSxH76lqhDAMsWMb7bxW84N7ZLb0lzx32xxNzVy5ugxGuM4UX4PpDsv9hBIrD8EwB9Hk6awgg==,iv:IZDHv68S2WiM9uVkwMVzP3myqXFMR3Pcw9EzYTiXiCY=,tag:TWF10CfphIz+6m9HCDkmHg==,type:str]
            CLICKHOUSE_DB: ENC[AES256_GCM,data:3qnW+j+iFiwik8IZ,iv:sTVTUgTpzL+ZXVaK0Dp+eaXA1sQ5Vzf63hZEKgWPOrw=,tag:1x5szTlM2mqWGO6ThSs6SQ==,type:str]
            CLICKHOUSE_USER: ENC[AES256_GCM,data:MmWGEcQa5xsxFph7,iv:Y5twavjm7rURGwHwtbXS9R4Vg6b243QqbNpcenI3mDY=,tag:x0BCC++r+uRd+bshyOSzSQ==,type:str]
            CLICKHOUSE_PASSWORD: ENC[AES256_GCM,data:jCSEXflP8HneYjaykse2/J0PEK+tNLWg7zSC6w+aeylPXGBQ/hYziE82y8miAJT0dUJEoFSBvhL3Ibk6mCqthw==,iv:YnC1c1N59EwftPrArE/WSr+L/s2JkIbu2QmNM5jiO/E=,tag:oOU6wPAn9hd6vMRm6UWCnQ==,type:str]
            BETTER_AUTH_SECRET: ENC[AES256_GCM,data:M4d19DLIDjoZ0vM/FHxsdgf9+e6CingWAUMcK7DAtuDqyFUpTlWNtZuAr+L0mPf5WZFHYDxAwzWHhAMvONAp4oRC46agCpqYOs2JNpL2PHe6WmEpDxakAg==,iv:zb3aoDXYkfKIizBHKgqYAkVaxKzyAwA+ffk23Mx6vZk=,tag:jAkKsVM6eSDjfv4p2CnLcg==,type:str]
            MAPBOX_TOKEN: ""
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLNGdkNGtOcVBUdlBWMGNS
            a1luMEJCekw5VVFMYks5MUxsNUx2MUpHMmtBCkZTbzZIc0FmR1AyY3l1cmpZSmNu
            aENYdU5BNVNTQjdKUXFzaUNRRS9ETkUKLS0tIGNIbndCSDRXZTg3NCthOGxxMStN
            amdHNGt0UkVIc2twK09QSGJMQVNsQ3cK7Pd+rd8+eBMyDL7bjmEIkMVX2Urv0Jxf
            S1n/6X93jtdEVmmbu7Eq7wFczz4EuVXNpcmT9JoLTo3BwwOBn6CSlQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-24T14:14:11Z"
    mac: ENC[AES256_GCM,data:2NHyiH13tfA5udPfUidOvOW/EYw6UaUk/kaO7n+gNhyh+ihBUMIxn/G3VDm7ixAYwR8o7kWXDTi8pM6Rof0lYVnsgmgstqRbJxjh1YoCfOMsFSQGx0dN7DDiDJvV8UnxtnHF9ccFvWptVKolcSAMbJ4V1WrMBKLlO04carVPqBU=,iv:ZofaPhZ7meLwyylxS0pyT8CURHMjNU/Orv7vYdMWUAw=,tag:qaoy1qY/veORxkSFgWtp7w==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
