services:
  pinga:
    image: git.radunenu.com/radu/pinga:latest
    container_name: pinga
    environment:
      PINGA_BOOTSTRAP_SECRET: "${PINGA_BOOTSTRAP_SECRET}"
    volumes:
      - /home/main/services/pinga:/data
    cap_add:
      - NET_RAW
    restart: unless-stopped
    networks:
      - pinga_net

networks:
  pinga_net:
    name: pinga_net
    driver: bridge
