apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hub-test-env
    namespace: hub-test
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:11goHJNJx9LekUkw,iv:rNa4sguwrHBWfdR9EcdrUX3lQBLsfbf5Tpc8kuLtxYA=,tag:dtfKJfeikPTVTsbHutbVMw==,type:str]
          stringData:
            RCON_PASSWORD: ENC[AES256_GCM,data:jfm+KttfnIuS1Gl1EmhBl57vEVQ2jqBOlEA+ZJgXiR3va9UphlG17h/jzg==,iv:nc6Dv5iSRIdmboRBJgUk31UdtoYF+rJCCwNP1qrFyIk=,tag:uuPLzpPXZ6k05va/Jbeshg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNjI3dUJhcmVCVnA0cWZ3
            NlJhbWdWN1gxQnpLVC9PbGpNaE04SEpuK0RRCmVJdzZkVjFSQS92SVJ2aXFCOGVH
            ZDB0cjlWa1ZxbXA1aGt6bThXLzFyTlEKLS0tIHdiRWhJSi9xcjFqUEJ0UXBuNDNX
            cWdycjFPVEgrblhMSmtnOGNZUjkzdlUKlzACqQJhlQ2WP0M2S9tezas7iwAVkp09
            o2xrHgRc8IVPuKNwVSTkVSeFSQyNOM7GG4PFs36yerQTeXp30yUZ3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZ1JNWlk4OEU3WjBjQnVV
            SGdldzN4S1I0RUIvb21xNVpGZ0kzQWpkdVU4CmV0NEloWmJFcCtDQzhOam9WMFdy
            VHhhZ3M0eHdkcE10RytQWHBBbnl3bkUKLS0tIFdkU051MGtTMmR5WVQzWm8vTlBO
            NlZzcjM1dm1qeGVwdEVOeUtsYkc3TW8KIqLvIeUHzCOGMSNcpDExyG0iEwXJ8aAW
            W2SpFAat4+Q+rz3KxBS8Ly86gwtQ93mFplAbCNWGPs2cP34J6RBW3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-10-09T16:00:28Z"
    mac: ENC[AES256_GCM,data:p3MvNMY5zVUQXJTlPeiPQoc9ckCTA6e05Zya4EYnE3R1dBHrw4dM70SPv5y/PcPzrrlE5eL2yka2q9yLR18jKy1jfRInTH7d7+rAWnQVWDIkJe53XSMM78XpbLSdnBr360nKa1uWwF5b4KVAkvyhDB0yPr2M6HFTJZId2lu3fgA=,iv:hyuGWVFZ1cYKuC38kZGw+vVHl9QH4FEpxhanPSCtrJQ=,tag:r1NTc/ReJO0UzFqLn8x/iw==,type:str]
    version: 3.13.3
