services:
  probe:
    image: alpine/socat:1.8.0.3
    command: ["-d", "-d", "TCP-LISTEN:9100,reuseaddr,fork", "EXEC:/bin/cat"]
    restart: unless-stopped


  frpc:
    image: snowdreamtech/frpc
    container_name: frpc-thinkcentre-health-status
    restart: unless-stopped

    depends_on:
      - probe

    volumes:
      - ../../../utils/frp/frpc/frpc-tcp.toml:/etc/frp/frpc.toml:ro

    env_file:
      - runtime.env

    read_only: true
    security_opt:
      - no-new-privileges:true
