{
	"data": "ENC[AES256_GCM,data:FSAdX1nosecvoJLP7i6NdcKwMqlgVcCF0lVjxoKQUTirCHPhUk/7GJUXSKT1GH+lJrcPRUr/mAFQLQoTvMNPW1cIP1gwAPMLpBN0AoIYY3Q7x+eJGrs2zWHoATY6CN+Q9mSpwG1/Cctgex0EXin7spK/TdyVIRiYMreqYHGTXX4r33O6yEBBaUynL+QpEepJDme74pQRa6O40ENW,iv:ev1tRr/y78h8tHjlD3sxlEsAWszwumLC/x3gwiRkE4k=,tag:NVtVFrggw0kAIQ5W2p3Skg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age14e77pf4jmmjxultr7xwupcqtcvdycwmpm3c7ac6vynf9vmnp6d7slnqsn0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SU94dzBOWk1GVDJKNzVO\neXFOc2tlUkFoYU0yZGtwbzR1OXNzOGozZnpZCnNQR2ZXR3pDcEpCbzVXWXlYNWtT\nZXVKUG5EN01USWsvZzY2cHRpeVF0d00KLS0tIEo5SDdHUzVXUHM1NDlUQTNhRXpZ\nUlduNnpuOWhueERUWkxkQ1gxQmM3eXMKDKoDSrRItrSPrZQ+r07W80bkW/ZhjkS/\nk29CKIoyf9nlvR2a+vfyGjWC7hbWhHHHtM8TuxinX3S0pE3y/qIiMQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-14T11:42:57Z",
		"mac": "ENC[AES256_GCM,data:OHjK8PXgYDnRmlnmlEtto06A4t8ekAaoiSnrBCDlsTNX2R7BJHq8rjkHGBkvM8VVbCNJg/QZTloom7IAsZ0nGBGvrBOYKXz9GRQPZ3HrMGoXGic70SPr1d379joNdj5+USHzHAQoaCjAvkbeaUx/CwBenbwaCb18ZsiBoakzD/4=,iv:BRaPkZXN+9UOBbJ8AeQMcjH5q9r1eXb1KrsO98AJpdE=,tag:u8l5UaqiO8unqzth5kxWLA==,type:str]",
		"version": "3.12.1"
	}
}
