{
	"data": "ENC[AES256_GCM,data:8CX9Q+L5ya9VRKnifk8I74uxTvcH7MVfxV5q7SQcS+29F4KfT3k8gWZ/hgT6BlqH9p7rT/3aH32pkoiuzjKtGTsu7yCmNX+mbMCSGs6c2ZwdyRQsjCFcyabjBts4yQc5EvutMr7vQmMICiIBOiDeYtbVyADvK9qqN/Xm44xgrv+GuhDDmg/dFNYX+R3SGVe9hZRf+jEtAhM5BGJb,iv:mde4ddqCIKspnRE61xJnGO/W26YZnWZy1lUK0lDm4WQ=,tag:jnvwBP+1pqx1vrey+v4nBw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age14e77pf4jmmjxultr7xwupcqtcvdycwmpm3c7ac6vynf9vmnp6d7slnqsn0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWjBrUHVJYWpla0hvTVI5\nd2Yzb0FtN2dvQ3lGd2xOMGh1bWxzaXRJUmhrCmpQRnMraFlPemh3clM3bk5TSmhI\nZkdYQXRBTno0cXFRN1UzcHF3RmorTmcKLS0tIEk2blVNaXdUNW83RTNST3JRK0E1\nTDZXNVdYUHBSRWpVSk91T1d4d2s5QU0KxCnt/eAh+r4I9xQXCtBOawCwiKYoWYA0\ndIwzEeAbZ54QZkSfrpBuFoumfA1mgYSyIVAv+I1yQKAiQ09hGmlHIw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-11T12:45:11Z",
		"mac": "ENC[AES256_GCM,data:dpsHsODggeNcg/Xf6G1wXhzWUPxtz8S17wQvp/P2qxSMjwkR76YkaXroZ3PC9SuwZrX8NHsSCM5NTTHpipYpOyGv7OBbcs/HF3DIN4UJSKeAGORqLkFHh/vrx2X29buUorOUSaHPe8Cz7tpT2mV0+5ES4rZLftzmJV4gMfZNhHM=,iv:qJN2OI0f9eyTCFqVmqgP32h20brSMwYooR7QklrsNS0=,tag:ZEft0gSEgTiEQGQxh2ObDw==,type:str]",
		"version": "3.12.1"
	}
}
