{
	"data": "ENC[AES256_GCM,data:7ZlaIe9IqMwCWxqds9JniX5TaWI4O/TjTIE7nT/HR7xKkwiYoOVBMBjm9JgDUDjUGcBCil0gxgkR5I/KlZYYIdGTmS5sVxU1FxVUzK+1Rt/a6tIJywITCfG3Fv2SR2agyRQGJZYBez9+IJ3a6bnMaK+df3lmUqUgBufumwZdrZ7N+vWT3kzhvaWveeoTdkgf1Vhwc2CwZUbJGGRA,iv:vSdiSsp+UKSoHgZABCcBrNrbZepVHMaJuixCZod9FOM=,tag:8W9aYH0MHhpUXdFlNnoHyQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age14e77pf4jmmjxultr7xwupcqtcvdycwmpm3c7ac6vynf9vmnp6d7slnqsn0",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnS09sK2VGd2EvalRQQXg5\nZGNIcngyR0c4MWVWYlhORTg5UllYNmZ4T0JJCnU0K3VHY0s5YlRHK0FlamxneXQw\neWszM1VobE9Lakp0MHJCYmV6enV5c1EKLS0tIDlGNWFwVno1aFhzZmpJZG1GaEcy\nTFBJWGZwb3ZlQ2ZyM2pxVDlmN2I4NVUKmHpWeTauI3IS7okyAOsLdlO2fp+R+Xvg\nLGIBlDlom3DgBdZzeToncFKowivy/fG1+3+BF+If8AcEh738UNTnXQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-12T19:58:04Z",
		"mac": "ENC[AES256_GCM,data:AZAiYbwMWH3J1zj9KI0ZgU2q8jcZknTopooAgxueiHYAOJ1eLQ1cM+kld7BfBs6miybrgeoAIjrH9goPi6KXn8wqEYrFd2jbGZFB/eApPLDZ6GP4YkwIBAfTXxQNB/qs4izwAftXASblNidbrBnf4UZwVrPaEGZqJOYJFb1BQmM=,iv:+HnnMKOERPIc39yRhQS6PJaq37bAdzjtuefIAriijCA=,tag:pK/dsZvO+jemjgtJOaMxUQ==,type:str]",
		"version": "3.12.1"
	}
}
