apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radunenu-com-stats
    namespace: radunenu-com
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:WDHeE39ABvXGpuBFOw9JuNVc,iv:zPXoA7fS0WCtC1IGVLMbMM1kVBnOvyWs++81svqeTJ8=,tag:swMWDjeXGrOw5dTLT+tnkg==,type:str]
          stringData:
            STATUS_API_TOKEN: ENC[AES256_GCM,data:I8BFU04nLy5iayTHLp2eYCJX70x1EE+48n6j3ga3ZBchKJ0ZgeUpyUb1i6jooW/uBxAevzt/u7iCYeICuvJyKQ==,iv:5hqQ3jfIIC47k2IoGZssQ9kMi/yZ3DIDemHka/2TppI=,tag:efKfm0AryNeZ4GtWknChIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWDdmMW1EVXBmV1hqb1kw
            UkhSd0J2V2djRTNobkdCRmFLZnRaN0x5UWhNCkRXd01QRDFtUEF0cGZ5Z0JmUVVp
            ZFNYL3FNUWdSMlpWbjBVUU56NGFxUEkKLS0tIC92Q3VxY1Boc3J6Vkc5WmNpSTUy
            Tm8vMHJLVWlFK1A1SEpCVE13YzFIUVEKBFlIGIzZv/Ui6r4WsQZZf0rXBIaDZVe1
            zQbmRWlXOpDuGT9SnT6QY1xwwHmR/YkG7rm3ppHPF8XoTBB0LSYfqw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCa0xWZjgrWkFqcE4xVjBn
            U3c5aitiY0xUV2EzYzMrNFJTQms4aTVuVkdFCjZmYm5ocEtGcjhjRElGMk1Dd243
            eVRhQ3BLT2VsNEpNdWZxZDZ1Wm1FV00KLS0tIDVFMWhGbzFDNmJJM3FXby9mSFQ1
            eGhWMFBZQTRBRlpXcHFhd2JKTkVhMkUKHiBOeziZ73jKKBglgnQJ1W7XCpJ5Jt8T
            aINu0fMlVW6telGBWw4vah1oySlHlwMpeXTFmZ1sjgzWoUovmDePDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-09-22T15:17:15Z"
    mac: ENC[AES256_GCM,data:ItkZJPUfjfr9AuFUPSl2nZ1uxuWneEmb0saI+UbN1HjSt40ZXnXoXYl7g2DLDYVnBzgKk0uiwLxQtqCC6bYp59dMMVJuBg35p5TNLIDyG8Y/PrESOhKTojGV9E/XW1w8oZLlVqbvOjgWZEP7OkpWo7GJybsLVWceTvKQLQWoRH4=,iv:mwIFAEqJmCLujxpE2f414a70c8ABJjTlUI6qPqCbcqU=,tag:+ofy8HD3qrj0feakUGJtFg==,type:str]
    version: 3.12.1
