apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: radunenu-com-stats
    namespace: radunenu-com
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:WDHeE39ABvXGpuBFOw9JuNVc,iv:zPXoA7fS0WCtC1IGVLMbMM1kVBnOvyWs++81svqeTJ8=,tag:swMWDjeXGrOw5dTLT+tnkg==,type:str]
          stringData:
            STATUS_API_TOKEN: ENC[AES256_GCM,data:I8BFU04nLy5iayTHLp2eYCJX70x1EE+48n6j3ga3ZBchKJ0ZgeUpyUb1i6jooW/uBxAevzt/u7iCYeICuvJyKQ==,iv:5hqQ3jfIIC47k2IoGZssQ9kMi/yZ3DIDemHka/2TppI=,tag:efKfm0AryNeZ4GtWknChIQ==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSTd2bmJEQ3gwbGVUUUs0
            NmJyTVhtUHJNVHpyb24rQVhKV3BCSzlhaUdrCkU1OFhjN20rSkJHY0lPb2YydHlz
            bHlWS3pLbGZqb0d2aFRHbU9DeklZNTgKLS0tIDZJY1hhRS9jUGRyVWpUU0RoQm5h
            TE5lRmE1UzFjOFNCbVVodG51ZXRaWVkK6pQwQ6oj4sZ/v21gCk0+lvcAr67G2zdw
            6/w0UqCR4VXr6QTbJ2CLL7B0cOevxbD+CxLV3gB41qw8TqcIsCt0cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-22T15:17:15Z"
    mac: ENC[AES256_GCM,data:ItkZJPUfjfr9AuFUPSl2nZ1uxuWneEmb0saI+UbN1HjSt40ZXnXoXYl7g2DLDYVnBzgKk0uiwLxQtqCC6bYp59dMMVJuBg35p5TNLIDyG8Y/PrESOhKTojGV9E/XW1w8oZLlVqbvOjgWZEP7OkpWo7GJybsLVWceTvKQLQWoRH4=,iv:mwIFAEqJmCLujxpE2f414a70c8ABJjTlUI6qPqCbcqU=,tag:+ofy8HD3qrj0feakUGJtFg==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
