{
	"data": "ENC[AES256_GCM,data:uWxhTac5i+xtmFa4EN5435qxJZIBrye2u6D1vTgzmxvwxMr+w23lEYgpElt6e8FRM4WVZR8t0YthswcMD/UoqtwOVEVmcBj53pVA552Y0VjRwQru+jFq8tNfyGYzTNClF3l382HtTfRWNzDxAUSLfVpAGYpYKBBgivEyKhynQ2H9v6Azl0I/pONCy6XA73rKcYa4jG0svUreIKSnc1saWRLAOA==,iv:wX2qY/rfXDMXLISyzH7uvSI3Zc03jwe1jQpIYeVqd5U=,tag:MK5T0C08jotLGJB2wt8IGg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cd5x4mtnurwwfsjl4h7clqutdv63680xrphgexvp0tdvpk4d79ystc0vr4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORnI5bUVKSEllNWdkMnJh\ndWlGUUhodmlvUmdSVXl3ZXVOR3JuemJuakU0CjVvUjZNUWVBS0JhS1RSVHkxZ2VL\nMjJMZzBXUWZ0NWdLc2R2Y2JVTnlCZzQKLS0tIHJDbW5mN2pNcTM3aGdNenFSVGFi\nQTZqTnlqaFhqUVBWMzViZFJ0bDN1VHMK27rAaOK7c6XKmbuc4kfrliuBcjRcE6IF\npsWg8ZkEieAc8jht2unIZ+qotcga9lYi3VXA2XRd4S3CxenbRmHrHA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-15T15:29:28Z",
		"mac": "ENC[AES256_GCM,data:onjBCySOdhPsKouF5jwNjdDqbr6p6RzRM8H4cYhRwJFJH04sdc0prDOqgUJ86IJRpYkqpEn9qiKIzBjWyJ14CWRm+sL+yYmBpeuSXBSg5/nZ7/3tmDuvOsCHTFjkoRZN9CNgHm6BO+SLaaOMClq43hotbJkhhXNytv7Wkd4G0A4=,iv:qC3mMfAmOTV6eVsXY4FBevmnBzKsMAFRtZQD5XJ2MCE=,tag:P45OKjWQ7IO85nFGaDdEoQ==,type:str]",
		"version": "3.12.1"
	}
}
