{
	"data": "ENC[AES256_GCM,data:w7NQ9CVsDzz23D2w1pYOrISylDiqDqSuyYNcZHp2NPgq6zadukgbJjVJKGUtF2Uj71GUEYkkjZlXHsB8bKiwYq5OgP+zyhNucGWlKENxZbO8bgccEOhBfCxjkNJCYZxhilnQGuPGqwqzGQMhdRTOHIzbsPaqoN9tEz6UkcWKH5Lg0pN9KCLcoJFjf5QuHW1CT1HNp7O8noDHcpV944kMpnGGNA==,iv:WzZdn1jaEABGnZD+UD2xs8SQ7qQ1c1doDJ4JJg4fAHo=,tag:dP/W5hNzhRo3WrG3U0tQ0w==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cd5x4mtnurwwfsjl4h7clqutdv63680xrphgexvp0tdvpk4d79ystc0vr4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQng3TWpBQy9JWDFRTXVZ\nTGF0M0VwY3R1a1JsTmN2N21qNktPSzJNd1hrCnNZMGZtTm5UUHU5UGJ1Wi9GUGVU\nWlF5TlFpNzVmWE5LbzBmYWJ2bnpMRmMKLS0tIHI3S3FDbWE2ZnJTV1BhNm1ySzlS\na0FvUndrT2N6bE96RzZteDRlOTY4TG8KJpbLjnnYqCsklDk97BBbr/2gzFiYi/8F\n7LwxBMcErBM+sq3QXEO+iiuQWNn6gTmYKUoUi6/IbP98WHZUsmgx6g==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-11T10:07:49Z",
		"mac": "ENC[AES256_GCM,data:DFemsbTwSL9jBKLfiW6YIAfcecsGeZgpMpFS56B1lFw/NG/yhQ/78vQWhetbGJ4+ILdU4IgP2YLfKQg6mEZ+tnkmIvzwyVmDyQK58Zc0MWASJXFf4FgzpCSNW0U2OUvGtNc5MSvbmS3gdHRWHAJUFucLyDt95vDWTHV3cbM9atY=,iv:LoaZsIO/PK4bn9CgBVaWkV0A5G/NEMrhxyQ8g5btpbg=,tag:2OsM3HFJacmPokghOXeo0Q==,type:str]",
		"version": "3.12.1"
	}
}
