{
	"data": "ENC[AES256_GCM,data:bCwzRSct2koUTjXe7/3dbxmYu7WzFdoyF+8+c7VPatGQtegndlJ2bw8eDE5EHyJxSeQ9C2VVHxSeFD+Xswlh96z2nbt15H4DCTwBYDL8lKbYAV1ALDW7kZFKgDswdVtSU9xThhwLvBmdrx7Dmku2V5iL9khIhAnA3FY25y+m/kNakhmSDRZcGjjakYnr7CfBf3U31ztyeE0VIC7lWP7Fuu64+Q==,iv:CnSccsIOrAkpr21KmkrfgqzBfF6rYyhbscSGLMepPgw=,tag:H03PVsrBlNI6pHiOgruqPQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cd5x4mtnurwwfsjl4h7clqutdv63680xrphgexvp0tdvpk4d79ystc0vr4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnN1VhcXgyY1B1MTRIaVFD\nWnRrYUN6RlZXTXBBUXBUVDJTd1dOQlBiUEdvCkFWLzVtQXdFRm4wYk9KbklMM29Z\nQ3g2VHNsMUpWVk8xNDhxM0g3TTlsc3MKLS0tIGtWV0F3dXpENXM0b2NUNFpIVEY1\nNnIzYXZVR290V0lEMU9LNkhOMExGTkkKIupiBNLwfEo5fWExf+tQutk1eZrAg9r0\nTWIeBzDLhhCh4FVb/SNo+y+c2+9SPbl+bf8/M6puCTzB1vwS8Xs3ig==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-12T15:54:56Z",
		"mac": "ENC[AES256_GCM,data:VkDS3l13af6DArKJbi/EnrFopwcSs0wTfC0INfdaUVATqajyWt3TvjEkY2WM9MHvpj4xdHgc2yT80PCZn9zDYa7uYJdwJQK8+6ivngFX0l254ei7i7Re2oV8bdtdCwv39JsXB81Z57i6WzwBjR1Xr8G89nyS5MmutL7p/udyTjM=,iv:B4zWwVO4qjvkblQEVxlHJXPQE2/ucmjkl+7F3BDlTZk=,tag:6QIUcVY/Fu4V8yywaB/rPQ==,type:str]",
		"version": "3.12.1"
	}
}
