services:
  vintagestory:
    image: xurxomf/vsds:stable
    container_name: vintagestory_v1.21.4_modded
    environment:
      UID: ${UID}
      GID: ${GID}
    volumes:
      - ${VINTAGESTORY_DATA_DIR}:/data
    ports:
      - "${VINTAGESTORY_HOST_PORT}:42420/tcp"
      - "${VINTAGESTORY_HOST_PORT}:42420/udp"
    restart: unless-stopped
    stop_signal: SIGTERM

  rathole:
    image: rapiz1/rathole
    container_name: ratholec-vintagestory
    user: "0:0"
    volumes:
      - ./rathole.toml:/etc/rathole.toml:ro
    command: /etc/rathole.toml
    restart: unless-stopped
    working_dir: /app

    depends_on:
      - vintagestory
