apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: searxng
    namespace: searxng
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:GvzcrGrIPJLDmz8tFmA=,iv:CwVY3mkjK94ylGG0MgzpBsbGidrEG2zWOrO8aFF9F0c=,tag:Td432y7JC+rnrL3JLXDiuQ==,type:str]
          stringData:
            SEARXNG_SECRET: ENC[AES256_GCM,data:5KdH9vFrlIogdCUBiOOsomWJop1t+lDCG0n4saSXiJZNqr5bqslCNy9xrbcXbmJah6BGnkDuCLSSnMkn8XXeCA==,iv:XtmUoOFR9+S4jXobpDpgZKASiUl5vMqPUDDpEbkrvbU=,tag:P3ZVcu0N6RMmpwb+j1E0Aw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbThDc2dWbGdXaGFpMUZn
            U09pbCtYeDhjck9uVG40WmVmYVAyQ2ZSbVdzCmZveTBPQk8vcUZtY0lOaU1nMGUz
            Ylg5ZFAvRU9KbnFFWjk4RzJhdTVRanMKLS0tIEU4bmxSK3RJMVZxSTE0L0lVNnZN
            eG9qQS9QdCtrZnFpRlF1WXl5cERxRFkKti6UfP0E3gMAaCCa0PCUxlnHew4198w8
            xaS/18oYkITVkkPRvM2aWBwBSzh68FxsWq6FkO1BY1qIO9XTUYqcuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-28T19:34:58Z"
    mac: ENC[AES256_GCM,data:VvbjytpyprDoKQoRQoVmnCCHrWSAf4FFzTQz+nDDyzOIGCWVEB0FU1LWWIzseAUXDdO8MmAlkauWnZlfb2j99heljX9Bq/gnKQJkUktMZGmeA6lCd056XHslJ/fkP1h7Rj+KcnTWk6zQhTdn2LdxRFUkVXwAm8GjsCrKE+R8AHk=,iv:7aVbGbvQlhxfxovnVkwRdVtCeFcycacRdsiQVZI1K2U=,tag:N+j/q22KmJeCirjF3L6/Zg==,type:str]
    version: 3.13.3
