apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: picshare-env
    namespace: picshare
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:5RlBp6xfetwsN1Z9,iv:QNCp1YW3sXNORHIgl6Px1MDryutDX5Jk0fQTp4F5Mus=,tag:98m3F9y99CqTl+EcqluSuA==,type:str]
          stringData:
            PICSHARE_CONFIG: ENC[AES256_GCM,data:9gGbLsfVrd2Cu353Su/Yqwqm9A==,iv:TyIEwmMqR7XfBGE/56WJUB/ncoA6GTbVJNzbByAOL00=,tag:sOF47/CzFoYQLwkO0wJOhw==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZ05Ma3dFQ2ZXaGU4NSt6
            a1JDcjdRZSswQ1BEZDZsVE42eFhrMHA2SEU0CjVmVWo1NDNEQTRMQmw1VVdCc2FK
            ZkxGYzVYWmY0WENNRHF4c1ViNTZhWjQKLS0tIG1IV2tOaGwwQi9hcUlhRWtYK2JD
            a042cDJQTUdodDJLaWZtbEJzM0NGNU0K/nYX5P9FKWF4InkEELjX4V59ThxUPFUy
            zdwg++dtxvy4rA+1JJnj8y0VfB9s3vvyK0vd9WB8Ko598+UWTcRHZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T13:30:42Z"
    mac: ENC[AES256_GCM,data:gHy3sjktnd4vu4GD+Eysj0cysTUY7WIb+GjrFTYO8jDVAtv/3/hkAeC5RmX0HeQANjoabQG4HU6aeFdnC9yxOarrJXfkLlIKvok36ota3reVzMJVBzJ9X0lm7AUOwdVtmcQDuadAni1JrKrC8uvuMbZZQGcZEdFNLUU+pqwlLNU=,iv:/4xxE3dQzKXZ4+17DxqTAP/YN+Yh5yyGIJLI55aRxGQ=,tag:GJd5CyPJG1gSZT6hoosVBg==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
