apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - books.yeetus.net
      secretName: books-yeetus-net-tls
  rules:
    - host: books.yeetus.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: audiobookshelf
                port:
                  number: 80
