apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: keycloak-env
    namespace: keycloak
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:5v75NV9jXWogKYQx,iv:WZ4hat8gJuYqcIA3oLu50U5gj6O2wn6SgKvUkWy0BB0=,tag:YWUDxsnLX7Ne6glHBhq9bw==,type:str]
          data:
            KC_DB: ENC[AES256_GCM,data:O3XOZo+QTFCHDAe2,iv:WqfBfATFPgdMQk0xxPkgTxSVTjel0Ny5s8uSenS2UHA=,tag:MUjRMikje8vKsYomkmaorw==,type:str]
            KC_DB_PASSWORD: ENC[AES256_GCM,data:gTthbZYlmg/1459LQACjiY8DX7lO5YNt3qnwigkCAJ0beTCMRpf/vH1cT4ZIMX9CNcKajT1X8gp3kPaqVaUvOsCpXTXak+blt4yqDzmxC1SlYbW9+a25EQ==,iv:y2MwvvB4WRaydjxn85f/6YLdVoZ1YBIq9AXpnxLZXdg=,tag:BNFTtgaZFm5lJu0HeFYZHg==,type:str]
            KC_DB_URL_DATABASE: ENC[AES256_GCM,data:SF8YbMJsr7EYF1Y3,iv:kDi7Mz3Fi/g28BHH1DzwSfoWDg0Ps9fPi4X3nUIEqKo=,tag:4gFsDs3KZO7Pxbs2rDqTAw==,type:str]
            KC_DB_URL_HOST: ENC[AES256_GCM,data:SDyVoFWw3PWUWCeq,iv:dtbhcv73MnjbTteAfLpO1Qoq0pd6KhOx4vTI7eb4yPE=,tag:eeo0yHYqCnphIFS2cxoJIw==,type:str]
            KC_DB_USERNAME: ENC[AES256_GCM,data:ThMppX471fskFISY,iv:orX0tlzdH/QrGWgwNvZPNA8sW/r5ZsHAJp+xl/W3vdk=,tag:7nhz152g8i/NMAZZh89qUw==,type:str]
            KC_HEALTH_ENABLED: ENC[AES256_GCM,data:Ui/g+O58gsI=,iv:iE2+Q/vZnAscTkEj6WftVHexlaMfYiwsJjssVPm3iAE=,tag:jlBPK9ccPDW7WsgdK2SyUQ==,type:str]
            KC_HOSTNAME: ENC[AES256_GCM,data:yg80tKBPNKLx07n6I2ykkyiA6QOGd21C,iv:bvvC6pZM193E9nmE/0IEnzUTospl1NZ278+2cKSEhPo=,tag:ilE0rDTJPzN9ywgwFLV88g==,type:str]
            KC_HTTP_ENABLED: ENC[AES256_GCM,data:bnGS5qAatCk=,iv:20qS0yWCtzbSMDnh3Z8ESSuHf2w4EgrlZ1OuseSw08Y=,tag:VMggOsjXSDOxyvbvsUBQIQ==,type:str]
            KC_METRICS_ENABLED: ENC[AES256_GCM,data:K/2llF1QE4w=,iv:XUeEqh5kd2yzoFnz0+F1S1ksnQ5GKrFu5gcvfYe9k3Q=,tag:A/m2LeBeBBX/zoKCoygQ9w==,type:str]
            KC_PROXY_HEADERS: ENC[AES256_GCM,data:wozc0nD4v8VWbWcse78yrw==,iv:H9i9tc2S/aBtYCyAKfAhyrgFRJjJx9W0cmof6osLUbE=,tag:iii9oqZhHwFlF8jCO7AxUA==,type:str]
            KEYCLOAK_ADMIN: ENC[AES256_GCM,data:Ac7C3nJzDMkebB/obkB3hlTr0hwqC8dE,iv:HwnwvKZGBCIuy/7uGCLwPz74hAJwjKMMMzVCtD7TsyY=,tag:I5nJu/zJTqOk+yzXYX0fcw==,type:str]
            KEYCLOAK_ADMIN_PASSWORD: ENC[AES256_GCM,data:y8YJ2BNBvi8ff/5I/90YSWtCtUCuiIX86Ys4pnGTr35slmkOIQhWRUDs3JrmMaxUEVXt+9o7REYqrbzu2jk0s0NVex7kz7z945m2fNRsXNQCGyN+DB0GVg==,iv:nugVY7jQUiycNVQBZJgKHxYEbXbp+Lr7Y48p50tnPdM=,tag:YAuVflyzlujXZRYpOLLa6w==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:ftmI/Oce4IRm1hq8,iv:QHkGyfc+OwciNpyhZkpeEAEX+uR4NZ15N/PVuGqBfow=,tag:B/itLEadDzgEwKPg9Txoxg==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:ZcsXOsL4LFhMFJewd8klPYdu8PFabWh5Eg8IGuHAlG+5Cu5C08qECYJyS+BMKDqH6HZc8oP4uzOQoNk9tdq4xQPqyUQ2jQABdEmW7MTUtcZYRFELtkAfAQ==,iv:YNQ+5KtoOoi3V/0FSnNpI6tIkZ4WbpPojd9BVrPyE3w=,tag:gTQQEDwLezhVsrpqZNGbCQ==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:H/npIXeypLp3mqoW,iv:kL3THxHjVK+YtR8JJUU8Yu1glrfLK74YFBlYiryKKeY=,tag:XSLzpfT7PHpKvU8oeALV8g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1dk5KckVPOVNSRTBnTnNH
            WmxVUkpIQ29NeWthaFZGTzk2TWFqNlBkSEFVCnFDaElmbW15RFhtNjhyZjMyRUZI
            MEV6Mng5Z0E4elZoclp5bVpKa0IwYlUKLS0tIHhzZ3JleGR6RjZCd09PSituQVYw
            MFI3TGVGRC8xdDFMWm50dGFDZW5lbVkKQCCscftt8/PyjpxSdZh+VU7QBXunoJiD
            tFRvCRAPXWIqAmrItw0cat+HqL5QRxA/zDa3ngloCU6ADt2/Wzap1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T07:01:11Z"
    mac: ENC[AES256_GCM,data:hcLETRu1Br5vuaAAIY39kL+CHdF3qJqHhdt306Zh+tGRGIlcyxkr7K+LlQWY+axuiFqIZamyNCG+E2ixU4nC2hCRcD0OenoNtf95jdxVUjvJufPjs3TNgbFFdE+Tm0XzsSpbJ+wnQnHXTOjACr16OqrBqDioVEnjbBwOjYK04uw=,iv:Scoy/6iaLF/lu+ez9+1kFSLT4wU9uaDT+TErruZt3Xs=,tag:uQaGcZm1gzN7C3hxLCUmJg==,type:str]
    version: 3.13.3
