# -------------------------
# Bind Settings
# -------------------------

bindAddr = "0.0.0.0"
bindPort = {{ .Envs.FRP_BIND_PORT }}

{{- if .Envs.FRP_VHOST_HTTP_PORT }}
# HTTP vhost listener for Apache to reverse proxy into
vhostHTTPPort = {{ .Envs.FRP_VHOST_HTTP_PORT }}

# Custom page returned by FRPS when no HTTP route matches.
custom404Page = "/etc/frp/res/service-temporarily-unavailable.html"
{{- end }}

# -------------------------
# Authentication
# -------------------------

auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"

# -------------------------
# TLS Settings
# -------------------------

transport.tls.force = {{ .Envs.FRP_TLS_FORCE }}

# -------------------------
# Logging
# -------------------------

log.to = "console"
log.level = "{{ .Envs.FRP_LOG_LEVEL }}"
