routes:
  - name: alerts
    path: /hooks/alerts
    room_id: "!jiIGBoKjsbcuuRAOtS:nuke.zip"
    messages:
      - |
        Event: {{ .body.event }}
      - |
        Status: {{ .body.status }}
      - |
        {{ .body.message }}
  - name: deploys
    path: /hooks/deploys
    room_id: "!jiIGBoKjsbcuuRAOtS:nuke.zip"
    messages:
      - |
        Deploy: {{ .body.service }}
      - |
        Version: {{ .body.version }}
