routes:
  - name: grafana
    path: /hooks/grafana
    room_id: "!jiIGBoKjsbcuuRAOtS:nuke.zip"
    messages:
      - |
        Grafana alert: {{ .body.status }}
      - |
        {{ .body.title }}
      - |
        {{ .body.message }}
