apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: joplin-env
    namespace: joplin
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:ok4N0G6+OZglpw==,iv:GkNL1hO3LyPY3hkwBgBCf+0uAH7Lg9IMyawBlPPT1Lc=,tag:syyXVxDQGra3t3t8jp9/XQ==,type:str]
          stringData:
            APP_BASE_URL: ENC[AES256_GCM,data:CXWayEzGj/XsolAqH8flv3UkJZY=,iv:XLSlRF5IxS67rhvO68oM1INJ/O/VPXH+5oUJuvdijyk=,tag:u4o1w0ETvLCMGmBHlD8rYw==,type:str]
            DB_CLIENT: ENC[AES256_GCM,data:CBQ=,iv:ivmolmfHSbrFvO9uWEmJ7UZ4Yrr0Clz83bnWyAKkkbM=,tag:VtHDVzNvrgE850Zue0HCUA==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:2QPrJ1BNXXcismgdBlBpKWOjs50n6KZ3dsL5g1DI0+NfWJU34l2EYw==,iv:cGAIXDrrX8in6Zv/8ybdN2+grtizbUFwYrW938y+ih4=,tag:2jJX0aKqAlU63y8aPXQMng==,type:str]
            POSTGRES_DATABASE: ENC[AES256_GCM,data:zi/4zMy0tBnd,iv:5NOs6z1sAspfvDF6tFjAhLxge+BzXV4cjx2sHLwLYP8=,tag:dlrwCvv24cJdgXdmPXc5Xg==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:kqDWNLVAxcA46w==,iv:DavPpyF81JTX2p8ajvbFyzQPA7ZKvwEkdNpzu4/yUyk=,tag:sC/eLekoXKvk4IojNkc+2w==,type:str]
            POSTGRES_PORT: ENC[AES256_GCM,data:4vlZig==,iv:AG8cCHBF36EDpeEQ1NinBgiYEgzZNTm4ZL+cJ7CoYkA=,tag:4Jv5XosXiuuZOWkajjlqIA==,type:str]
            POSTGRES_HOST: ENC[AES256_GCM,data:+1bNmvb8h6SU,iv:aR9z+ctKBI68s6BZ0ujyUf8pK2EqcY+tqNvBJsb9pwI=,tag:zD9jalykOyE2o7hKW16Z3g==,type:str]
            MAILER_ENABLED: ENC[AES256_GCM,data:z+1PuRM=,iv:Ebz6bXiI553lQs4vlA7FHCStsr5mDrka2inUSgzbV8o=,tag:+3DPcGOQUDRmIAHkEFEqDQ==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:T515NCRQOMnF,iv:oREtu1f4rtoTVP45FKZu1gyxtvkhHq+pF15ILS30AvM=,tag:5aE0wv8mAbP7ho16l6QG0g==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVTg0YmlmdlVWWmtRVjUv
            Yy9HaDB0Q3VRMTg1YjBqdzNMbVdHYko0UVc0ClNkZWdSaWRhUW9YTVBXSmpqM0lp
            SE5oR3NtQlRTM2ZzaHlaQmJYQm1DUHcKLS0tIGkvQklHODFHaGZpeTJLSWpSVVNT
            OXgzZURZODdCa3ZJY1ZOUDRQNmtyYkEKIwci++LnKZIIpASovUMZ9jg6BCJQu0kL
            D35QqnW5++Lnh61K5ogP6uKCCUTwxBMdwFy4TRZH8/wr2ZmTa73OeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T13:30:42Z"
    mac: ENC[AES256_GCM,data:yJSZnHEQgxFzwtHhux7JoyZGqAeMrXRNqxc57FRGflde+tzMkEUSglE+ntZQ4KyLrBT2PbH+Oumfy2q5UCtv3+6iMySolpY8NIMg50yPR1p0AzGzvu+b1OS577Cymp9xxGqnjq87dM64SW3Cn/cAloWKNOXuKZVsov1prrSgMJU=,iv:WBrHqjvGuliIgPYrlIq3fKj06l8DiKZ7TGQzf6mr7uo=,tag:eROywGJ/MSiZhj7JgzlqWQ==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
