log:
  level: info

runner:
  file: /data/.runner
  capacity: 1
  envs: {}
  env_file: ""
  timeout: 3h
  shutdown_timeout: 0s
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  github_mirror: ""
  labels:
    - "linux-amd64-thinkcentre:docker://docker.gitea.com/runner-images:ubuntu-latest"

cache:
  enabled: true
  dir: /data/cache
  host: ""
  port: 0
  external_server: ""

container:
  network: ""
  privileged: false
  options:
  workdir_parent:
  valid_volumes:
    - "**"
  docker_host: ""
  force_pull: true
  force_rebuild: false
  require_docker: false
  docker_timeout: 0s
  bind_workdir: false

host:
  workdir_parent:
