apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pbin-radunenu-com
  namespace: privatebin
spec:
  secretName: pbin-radunenu-com-tls
  dnsNames:
    - pbin.radunenu.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
