apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: privatebin
  namespace: privatebin
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pbin.radunenu.com
      secretName: pbin-radunenu-com-tls
  rules:
    - host: pbin.radunenu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: privatebin
                port:
                  number: 80
