- targets:
    - cadvisor:9101
  labels:
    host: edge-grafana
    site: edge
    role: edge
    os: linux

- targets:
    - host.docker.internal:5995
  labels:
    host: thinkcentre
    site: homelab
    role: workstation
    os: linux

- targets:
    - host.docker.internal:5992
  labels:
    host: hetzner
    site: hetzner
    role: app-host
    os: linux
