- targets:
    - host.docker.internal:9117
  labels:
    host: ovh
    site: edge
    role: edge
    os: linux
    service: apache
    webserver: apache

- targets:
    - hetzner-frps:5993
  labels:
    host: hetzner
    site: hetzner
    role: app-host
    os: linux
    service: nginx
    webserver: nginx
