- targets:
    - node-exporter:9100
  labels:
    host: edge-grafana
    site: edge
    role: edge
    os: linux

- targets:
    - thinkcentre-frps:5994
  labels:
    host: thinkcentre
    site: homelab
    role: workstation
    os: linux

- targets:
    - hetzner-frps:5991
  labels:
    host: hetzner
    site: hetzner
    role: app-host
    os: linux
