services:
  frpc:
    image: ghcr.io/fatedier/frpc:v0.65.0
    command:
      - -c
      - /etc/frp/frpc.toml
    container_name: frpc-hetzner-synapse-metrics
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../../utils/frp/frpc/frpc-tcp.toml:/etc/frp/frpc.toml:ro
    env_file:
      - runtime.env
    read_only: true
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
