services:
  website:
    image: git.radunenu.com/radu/radunenu.com:latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DEV_RADUNENU_HOST_PORT}:5757"
    environment:
      CONTENT_ROOT: ${CONTENT_ROOT}
      ASSETS_ROOT: ${ASSETS_ROOT}
    volumes:
      - ${DEV_RADUNENU_SITE_DIR}:/mnt/site:ro
