apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hemmelig-env
    namespace: hemmelig
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:h3V4hrAJrkswBFRG,iv:nhZyATRLBxm5F4ot+ClGX97UV6ItedPjP7Ard5ndf+g=,tag:EOc+5OzOxqKkZAlmROR5JA==,type:str]
          stringData:
            HEMMELIG_BASE_URL: ENC[AES256_GCM,data:aMearYpf4iiU2akDjzGwm2r1yiJXfzfT68s=,iv:RY1PGFSBUBXXHkLSYb8YBJYTnbwUGUfRhrOP02DpdW8=,tag:LjghyT+lkaSQphzDzzbzEA==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:6dJoJ9zE/zWe5zBAyzQei3JLXxrn9VHyZ8AuRxdJ,iv:hKN7kvwv/2iZw3m+Dek6HzJ6NbUcvCTKhAZWgGK3vjo=,tag:BmVtjgsOvP8xqSr4/mRZbA==,type:str]
            BETTER_AUTH_SECRET: ENC[AES256_GCM,data:vA189wwfw3QP67ReXZ8Q0DLtF3a1F0Tczotif8rNwyykdE6t1Tg62/fQ0niBRYJcRmtG33bRTzvEXwwxtgLuKw==,iv:TP9El8H08pJGcxDSeGTB6TwNRv5n3NjHaCo69WbTYmg=,tag:f2Mvg8MIaPtgc+/xcQv6nQ==,type:str]
            BETTER_AUTH_URL: ENC[AES256_GCM,data:YfV1EUlRlbnwHnPR+fOqPL1hKLbyQaooGoQ=,iv:Mwtgolj4g4K6ERqtC0/uefB/GAbP8/e6hlIpRhcQUyA=,tag:9ef0ae+y4KzVot3cMTw3FA==,type:str]
            NODE_ENV: ENC[AES256_GCM,data:rD2/nQuJlCVp9g==,iv:h7y8HpPE5CbK1tE7w4BCDEIiDzR7K4uWm+zB3O//uDE=,tag:PbEWQSAQWxCbm8z45YH2FQ==,type:str]
            NODE_VERSION: ENC[AES256_GCM,data:C3pSmEvg,iv:A/baVHssr6F55LnJoKCX+cKUb8amlUawLT8muHmobzo=,tag:aaslIXkYmDqy3in8WTZ5mA==,type:str]
            YARN_VERSION: ENC[AES256_GCM,data:QTP2DgC9HQ==,iv:Zx266MNJ/QVlayBkZvR4vUirpJQFgU8XlowiJeyxoAE=,tag:T/BYh0uMF6fOvi50KD782g==,type:str]
            PORT: ENC[AES256_GCM,data:maB8LQ==,iv:sfBRDEG3gMtZ5EJvCi0Wwpso6SNVkV7YbilR86P83Mw=,tag:Vi2e5TS2vhgys3umPJmxKQ==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqREwwME4zMi9wTVRzdUky
            b21sMjN4SVI0eDdlYXpFOEIxdm5oOWhUODJ3CkVFYnh6VGJjUys1d05GVDRnUklZ
            R2pJczVSbzRBczVZV0xRMlNWUHpmN2cKLS0tIE5IVjRQbzFLOWkvUFN6c2tpWUdQ
            V3dETlNDZlo1NXZRZy9xcXlaODR0c2cKtl5+hi28EkOBYOFMO1sTEl7NskSqFLhf
            NtiN5zCnYhABgzJIetTvUBgjDzkG9rgWB3LJDK41pO51Qeyd1qs1Lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T13:30:42Z"
    mac: ENC[AES256_GCM,data:B4ph8rpqDqSUE/p6P+8zTDcwVbKIWKJ4W3Ka/rBSnQk1GWa9UbKr6rMgs/qxVEqzXspRpTt2+3MSpUH1jW8BBGdxYs9YS8ZryYbbhPRKnjLQMYvEygIJilPqPZAT79WTJ5Aj1D7ncj0CedplZq4pdRpkSF052EOidPtkN09ZDeo=,iv:7M7ZkCj5FYuYLlqsrgk1BvRuiIv+XqZgrzomcfvXnpk=,tag:EAIro9XanFOAjSZcVrY51A==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
