apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: minecraft-rcon
    namespace: minecraft-skyblock
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:BjgSV/T2w/X/LBKGOjM=,iv:io4DeTW0S8T4DmdMGiSPeJ6teVIXi+wWzvRfo5XTL6Q=,tag:adGLJGWsVEV6yaAdQqOg1w==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:yMXd3+UOPK99Eru0BoyiqsHBKqyfQnN0VDTr70ie898=,iv:KfiwixM20PLGA+yV58GbFsYcI4SGFpAfZdk546+nxvw=,tag:LnBU/4TyUY6+EBGDJmhuSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb2tWdlpkOWFicm15VkhM
            a3NNV1BwTmMvN25tMGl1ZVhxa3k0bW1UWjFNCndxUkM2b01HTjhkbGJKRUlocDcz
            RWxYbkV4NEdOUUhvbnJtQW5oa1U0Z1kKLS0tIE1oZlpLRTF3a0RqQWw1RjFEQjZ6
            TjMxNEo4emV6MGdNaVdqeFlkWlhVOTQKUhSsajqiSgTottbpig7nOWhs89SuoWqd
            B9y0ht84E+WiqEWRmAhloBVrWwzS7KXn0zir6PYXw1pcaLsYwv9yoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWWRaNHRHYzhwbGQyRXM4
            eGNJV0daN21tKytRT2pHOThZOUZCYStvZHpRClZLZjFIdVdUR2h0UnV0UjBCdXlt
            emZxdTc3MlpKVEVad0REUVI0SVJWNk0KLS0tICtzdThLWUNFc2FWTXRUMW1UN1pJ
            M2dGTGlqa2VpSmJWeTg5b0JtU1pkOFUKrLNpFpY2WIEemxGwtkovjhBo6PJlNbmY
            yngNBkgBy4qJjkjkNmcwwc+mNR//2BKXIIsIiQgbhh5Poa9qmXwRXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-10-06T16:45:13Z"
    mac: ENC[AES256_GCM,data:9bxAxR+Po9JVARKQwY484RoLEHqfv1eipim17LX/mmw1zF21DdNQTMJbxO/TlVQSrQ43yfgEI/Z2Z7GHII+jMAS96Djmzmchwa+NN/TBTiWmmsLihHErd3SV6jmO5n0WuR1WWlqs7bv5yZRLzgX6TSSLKK12rg3R4C+tMlfkmX0=,iv:x7Hbz+DGIUD2i/DGnRXUHl8RXLSlHkxqPEmjnMpVDfI=,tag:0oMOr3EgpWPAmM77wDu0OQ==,type:str]
    version: 3.13.3
