{
	"data": "ENC[AES256_GCM,data:FQ30XE5eYSC3Jd81WjaXbapH2fHmsj937xYTp+gr5iuFWaKcmDzEknGVNFgVujOelln/PsvZ6ZUkwoFFA9YpxuvlFcNuoBEaLKtIW4jS0IOdxbW+pCOWV+baKIJEuHrRdehg5gZ6ljmHFgK2B+vZuchy11Zgrf7aJKxwca3i5TuhBOHvHPz/ls8Fe4L0W/gFi/aTyESnvmM4j7F0j3SyR+P0EMc=,iv:utWHvmSBEa0ag6H6wuyUhX5vzwtMlT+9rABTk672cyc=,tag:rz1Mh3MI9xpzDu30LdsG9Q==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19534xcs4gnxs09y83lqxaj4flm6x9wfngu20wgs4rm7hyq5p93estc8yqf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVFJ5UmRCK2pKcTl4c1o0\nSFhwQ2ZhanRSNnBVZTR3YnA1NzlCUDRFTW5BClRMNWdkRVloTkN6cERvbDIzUjl6\naFRFSWsvMndTb3k4b2c0eUkxSFd6ZXMKLS0tIDFwN3dOa3E2Ty9hNlhBbHNNM09t\nd2p3eGo5M0oxYmVGWmRJNW9Ea2NQQWMKWllP4sn9/ASTgQ+GiYh9T52nPKaAVc4Z\nwgDq1D6bEx1rcOGNKyw6U/SngKkNGOwG/jtFrRhIKaXFd466bxlPcg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-12T15:54:56Z",
		"mac": "ENC[AES256_GCM,data:IbXzwGPoMZZvC5dLNA3oyf/6+5tr63lDDtqYUxRAAVD6cz8sMRYd1AjyTeUdr48wzh8yKzRz4SQVdyn8MNA+ZJCAuzN5pp9Vou05FUqeBXUEkfKHL/NejgNE7kqr7f+wSiRpJKlt/pNzRuGHH5udL1Nag2mx1UFwMJeoGV3PbAA=,iv:rQRgDOxvLwu/2dSqQgNGOqbVHjrdbzWHxJ5kdRC2BHo=,tag:CUY+2x6LfhVzEW9giiqeEA==,type:str]",
		"version": "3.12.1"
	}
}
