{
	"data": "ENC[AES256_GCM,data:mhI1cE28ThMoOPDivXRSEz4+6SIS+wOon8I01LfJbkVBb7xqUF6zM99NH9AD2hqry5loMmoQsU0B6VO6V2cOpvHu+9qX54qzFAoEgTXi/7QhCg6tYK0KFlNF5j4W+F9hgGDQmG5gcEVXrlw4qtMbRFT8sHTyysrKKYQhZ8457gnscDbHVRnFVV0qQtteJRjr2c/Oz0repbe0SI58ge+9keLspW0=,iv:bUfRhk7M16rM/erM+ZOcEcBHoQjkn0y+XPmWfP8Z9w8=,tag:zcsAVcvaJj/PyZ5mcYafMw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19534xcs4gnxs09y83lqxaj4flm6x9wfngu20wgs4rm7hyq5p93estc8yqf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbTNHWGhHdGczejFJcU5Y\ndXZUcm9UNmFqcDZNbkJTTURvTWFoMmpyTUJrCkFyN3JGSWw0bm1samFBZ3ZPb2JO\nYTF5ZDRYZ0dBeDRpMkhBbDdTa0Q3MlkKLS0tIDJ1UUZ3TTloNDUzZTIrMkozRWRj\nQUdhZUIydlZ3a2dYYzB6dUZiOWQ5aTQKJOrPRvj3nGPM2FEgwIDBW2EXHvgOzwUr\n8R+h5WfFVzxddXMlroJKUnJaCmpNu8wXhBfm3X6WCfI7JwrR9gGR3w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-25T08:38:05Z",
		"mac": "ENC[AES256_GCM,data:hEk/+uxfQXFgpZIlW81xCbR1KmwtRfn7qOXI5pD/QDq6Y55DjhjbeQpF5EO2MTaxXq6PlCuCmoawr2mtddqJShKSekD5tB6RqmNFvoF8es0OWwwZo/ye5GPfMmKzFPwuiniJV4ZOkD4DkfehX/Bw0k6KYOQg+dlnOn7Gp4Agbsg=,iv:xz38eZQ8YrASMEETaSIS2yDCXmTaKZ0SYyKbc2mq4QM=,tag:mAqE3yCPL2psxRRxIZHhkA==,type:str]",
		"version": "3.12.1"
	}
}
