{
	"data": "ENC[AES256_GCM,data:FXC/HxaCGnQrHN2E00zhjgWTjHoJ9+4tTq9QJbAuZ6U/hbhTVHJlsfhRb2iBt0Ex7V/yO3M6lTuJ57Pgg4+d+bj7FxE7AIXUjaIAxCDWvLifxkbJ9AOwPKtpg1D76kHsSaxoUifshhH75nWTlLV9zJBvEqW/vfIdooGlpFA4aMNfoAB87cDTEARthFtsSOlwKmitcdA5y1Oi4QEN4V+jLdK615c=,iv:SelIRe5s4v9qhboOGQdTj98PghVjpxD7pQ1bFQnjXUY=,tag:PIsRX4pw5d/zDUBP3XfrHg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19534xcs4gnxs09y83lqxaj4flm6x9wfngu20wgs4rm7hyq5p93estc8yqf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTE9DQi8weVZMdHdsVEZV\nZFQ5QU5GVDFwVm8zOWNwZmFMNXhXZ0QvZlRzCjdaZVBqaGg0U3pmemV0OEgxK3JE\nUXhodzFRYkxIK3ZjTXpBdkF6cVN6MzgKLS0tIGVZOHZDVnRlcUdUeENFM1FqdHZ3\nNEtkdUNpOG9JM2wxazJvQUdmeFZjRHMK8fuGPRrTlUULM9B9jPvWnv5seBEnrNck\nAxTfSHhgHz3kLmjpD1P7fmGuIGSougG1Wb6GhQAXrD+zuVoswRKdHw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-11T11:58:34Z",
		"mac": "ENC[AES256_GCM,data:D6gJn/RKYmutOft0/CqTo3zlgbosHxHeq4uaMbzsVeQl5YXCM37Qh4qNEUxYjVWZkL17lxHEPR1DXp1wx/kQj0K0Wxlxo8LvNCldw+YpuTwt2nnk6g5LY4Wk1O7EGpM7gZZ17zz6+kEASYqf/jIi4gDPnsjLXDwjlqjIvuz7+Zk=,iv:2iP+dT4hqgT06idFvFXxt+bIFntxthROzR4K9ldPffI=,tag:vwG/U5kzJ7CeFNKncSZrBA==,type:str]",
		"version": "3.12.1"
	}
}
