{
	"data": "ENC[AES256_GCM,data:4ztZ9RO55lV8X9VgSrGMfJXHoEGPHrvlyPl6cnUZ/S1a0iJL8C9m+x3CJVHGMbARsChu6wrhyzzeYHNPd2+4885aQYTXN5mF66EAzr/031fq9KBZR54B0smwyUQOPjO04PrVQw2yPhDRArUK+GVpmIjL7xgXkIlRQOUnJbvP/10JhBp7DV70Tf4QbjWesi1H+9yxUJxZ5VjkMwcY7nrD0FMOgw==,iv:fYmkz8uri5dy2wuLJCvDVUjwQC1mkpd3IHsrkvwkkKc=,tag:9IkYf01qygQEaXJRvzi5LA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cd5x4mtnurwwfsjl4h7clqutdv63680xrphgexvp0tdvpk4d79ystc0vr4",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwd0tQZGZ2V3NoNE9PMkdD\nZG5tNmNxS3F0ZnI1aEVYWFdoZzNBVnBjckRVCnBOWXBmU1h1bHZFcGExRHd4dTFh\ndkxWYktDT2kzd2NaRHdxZm5pZmEwaW8KLS0tIEg5RGhiWmtISmRDcVFuVE5ab001\najI2TkhjQzJpUXVFSkx4VWhDOVJtNHcK6Xk8cmKILpYAK9+i1Cf1F/jAViafR5PD\ncfjpNCk0xciQzWGI9KNowD3PBXo4QTmn10q1GrMeLisSQIptWTD9ZA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-07-01T13:04:19Z",
		"mac": "ENC[AES256_GCM,data:LEmHqLQtHXJJgNGCG0SDC+DLHsZxovNlUCecdzpsnlX5QcqhBMSbks+O31ROO4T+bgGP6TrezudZ32FVce8i4L1AQ9PkQq3KorShGx5AczKB9lFXJSweiAqQTlQRk0IopdTiJmRh21OLXps1vtjWmYXUrh4Kgui8MKUrqSpBANE=,iv:YbS45x1vUSU8njEY9GIZumkuEJFQX/G2ieAjY1yFiHw=,tag:HA9DFY4ibIMq1ED/13T3YA==,type:str]",
		"version": "3.12.1"
	}
}
