apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gitea-env
    namespace: gitea
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:UiUizMpZoGYl,iv:PB/k1ywFHMFVFJQDvzrYRI1TvizYAhWywqdXgW297MQ=,tag:vMtOLlzhRYeYDQOMEkI/kQ==,type:str]
          stringData:
            USER_UID: ENC[AES256_GCM,data:a8uF1Q==,iv:KGLKAiB+e+0yU2C4t4JAUM/PvXV47iS8zRZ1djsQ3Vw=,tag:halCwHTUiYIEfM7HFr+/bQ==,type:str]
            USER_GID: ENC[AES256_GCM,data:4J6/tA==,iv:eqBBzvXndr+pgMhtyk3JATcjjPj2UktLFz4hULC1Ksk=,tag:OQfYQzyqqLr8906wpQ+yOA==,type:str]
            GITEA__database__DB_TYPE: ENC[AES256_GCM,data:om0BF+ZyWsw=,iv:6EdtTenmpOH+6MBvTK8t4ONAxSYQ2dfuY+pcYoYXF2A=,tag:t4DW27BMZ9/tz2FNltMSDw==,type:str]
            GITEA__database__HOST: ENC[AES256_GCM,data:g0A+/E1lhA==,iv:/mlfzD6JIicxLIYo0PmOyrZK22fe//suO/PDa+yNgRw=,tag:mPjZPi8pb3aPxEK0yXDuXw==,type:str]
            GITEA__database__NAME: ENC[AES256_GCM,data:6h4Pq17R+sg=,iv:x/NOp+6u+hQ4QKSdDz2ueH6HF+KfwHD9enSGbyRxGds=,tag:KhS2aw5S3aVM5jLgpMKwjQ==,type:str]
            GITEA__database__USER: ENC[AES256_GCM,data:cgHW1aVhVWVI8R0=,iv:cpwtIIH5fKhQEgcxz1Cv8VStIOkfWHEnNtpGTrPuwRE=,tag:Zy5aZKx+JGazgA2GEv4asA==,type:str]
            GITEA__database__PASSWD: ENC[AES256_GCM,data:LhX9lk8e5GT0bxJXh34/XoatrzwwXKZdrggz77HEdE0vz2IqWA==,iv:7OEmfUn5eir2ITMXMoV/H5lq5xIin1KJI8JjtTcWZxU=,tag:ZqOn3JQlyzkBF/t224L1hA==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:RrX5Kh8g0eFlhNI=,iv:mQGHXqmTs1CLgu5aPZW3H4X2l5sD9XUcIwl36/5lm7o=,tag:9p/bmjL1feB2JuRDrTTIDg==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:UVC4cO7cu4p3lgtM9VlOabd3J7gcdg1Ax9ly73YLi5YszKi2Hw==,iv:+cstd5dXQIg2FgSC3tUpSgWJVEzuM0vi4V9wNyrx8Ew=,tag:PIIS7kfRN05crXavn+2wNg==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:g/71c849JDE=,iv:SibyWdPcaIM/iW+gBbhIJVQvULrWFTuai+/EooTTbgs=,tag:PD1YFNktdUXO2r6oosZEFA==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZmswY2liRjNLYXdncFIx
            TXpWR0JHVGtHVHdvdVFXeTZMQ0pNaDdqd0UwCjRKRHpjV1ExeFdXOEpMaGxDNnh4
            Q2RDSEphR1lDR1BWcE5BbDNSVEUxUncKLS0tIFdvWk1jeXplVkJKQzBXWmlTaUd4
            MFJ4RVdEN0NXOUwrcGlMUUQrdTlRamMKm8jkAlV8gGs878zhyBF/usVvdqurTe4T
            FpCLpnIqH7/Fp3cmQjNbw1zmb/NcFNSpl198Qx97+FlZk0SQ/uu4kw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-23T13:30:41Z"
    mac: ENC[AES256_GCM,data:59IxG8kOK3QNwI/aDqhRQhsz0jClsRRSPVxyOPuMsTZKHGtWaSIDWl8z/hz+nYL7aX6IWciAs+7rib1MMiDxCZL2G/PfciPKGy4MdMHkApPgwcEcNfrz3Pj9tpsLUARQ0WkLDPfB7Cm6Cpli+TK/1hmkitFIa35FH+CYPoNHFIg=,iv:1oXx29h+YruSDg3/gRHGSCmGAXT78vD9JVigLY6byo0=,tag:faWaUi1fY+/zBOSrftuy7w==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
