apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-postgres
  namespace: gitea
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector:
    matchLabels: {app: gitea-postgres}
  template:
    metadata:
      labels: {app: gitea-postgres}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: thinkcentre
      containers:
        - name: postgres
          image: postgres@sha256:156f0b253fd61366d5fc2107ad45955027d5612f695a8436ce20167f3fa79bff
          envFrom:
            - secretRef: {name: gitea-env}
          ports:
            - {name: postgres, containerPort: 5432}
          volumeMounts:
            - {name: postgres, mountPath: /var/lib/postgresql/data}
      volumes:
        - name: postgres
          hostPath:
            path: /home/main/services/gitea/postgres
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: gitea
spec:
  selector: {app: gitea-postgres}
  ports:
    - {name: postgres, port: 5432, targetPort: postgres}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  strategy: {type: Recreate}
  selector:
    matchLabels: {app: gitea}
  template:
    metadata:
      labels: {app: gitea}
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        kubernetes.io/hostname: thinkcentre
      containers:
        - name: gitea
          image: docker.gitea.com/gitea@sha256:87a67ee09d3ae0d1df5fda5dcda3e2a1f9236a45b0a59025d6e00e46adc43bef
          envFrom:
            - secretRef: {name: gitea-env}
          ports:
            - {name: http, containerPort: 3000}
            - {name: ssh, containerPort: 22, hostPort: 222}
          volumeMounts:
            - {name: data, mountPath: /data}
            - {name: localtime, mountPath: /etc/localtime, readOnly: true}
      volumes:
        - name: data
          hostPath:
            path: /home/main/services/gitea
            type: Directory
        - name: localtime
          hostPath: {path: /etc/localtime, type: File}
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  selector: {app: gitea}
  ports:
    - {name: http, port: 80, targetPort: http}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-radunenu-com
  namespace: gitea
spec:
  secretName: git-radunenu-com-tls
  dnsNames: [git.radunenu.com]
  issuerRef: {name: letsencrypt-prod, kind: ClusterIssuer}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  namespace: gitea
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - git.radunenu.com
      secretName: git-radunenu-com-tls
  rules:
    - host: git.radunenu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  number: 80
