import { readFile,writeFile } from 'node:fs/promises';
import { resolve,join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
const registry='https://git.radunenu.com';
const applicationRepository='radu/savehub',themeRepository='radu/savehub-keycloak';
export function checkedImage(value,repository){if(!new RegExp('^git\\.radunenu\\.com/'+repository+'@sha256:[a-f0-9]{64}$').test(value))throw new Error('Unexpected immutable image for '+repository);return value;}
export function releaseImages(manifest){const a=manifest.annotations??{};const application=checkedImage(a['org.savehub.application']??'',applicationRepository),theme=checkedImage(a['org.savehub.keycloak']??'',themeRepository),commit=a['org.opencontainers.image.revision'];if(!/^[a-f0-9]{40}$/.test(commit??''))throw new Error('Release lacks a tested source revision');return {application,theme,commit};}
async function registryToken(repository){const url=new URL('/v2/token',registry);url.searchParams.set('service','container_registry');url.searchParams.set('scope',`repository:${repository}:pull`);const r=await fetch(url,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error('Registry authentication failed ('+r.status+')');const body=await r.json();return body.token??body.access_token;}
async function manifest(repository,reference,missingOkay=false){const token=await registryToken(repository);const r=await fetch(`${registry}/v2/${repository}/manifests/${reference}`,{headers:{Authorization:'Bearer '+token,Accept:'application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json'},signal:AbortSignal.timeout(15000)});if(r.status===404&&missingOkay)return null;if(!r.ok)throw new Error('Registry manifest unavailable ('+r.status+')');const chunks=[];let size=0;for await(const chunk of r.body){size+=chunk.length;if(size>2*1024**2)throw new Error('Release manifest too large');chunks.push(chunk);}const bytes=Buffer.concat(chunks);const digest='sha256:'+createHash('sha256').update(bytes).digest('hex');if(r.headers.get('docker-content-digest')!==digest)throw new Error('Registry manifest checksum mismatch');if(reference.startsWith('sha256:')&&reference!==digest)throw new Error('Unexpected registry digest');return JSON.parse(bytes.toString());}
export function patchImage(source,name,next,allowed){const lines=source.split('\n');const matches=[];for(let i=0;i<lines.length;i++){const m=/^(\s*)- name:\s*([^\s#]+)\s*(?:#.*)?$/.exec(lines[i]);if(m&&m[2]===name)matches.push({start:i,indent:m[1].length});}if(matches.length!==1)throw new Error('Ambiguous or missing container '+name);const {start,indent}=matches[0];let found=false;for(let i=start+1;i<lines.length;i++){if(lines[i].trim()&&lines[i].match(/^\s*/)[0].length<=indent)break;const m=/^(\s*image:\s*)("[^"]*"|'[^']*'|[^\s#]+)(\s*(?:#.*)?)$/.exec(lines[i]);if(!m)continue;if(found)throw new Error('Ambiguous image '+name);let old=m[2];if(old.startsWith('"'))old=JSON.parse(old);else if(old.startsWith("'"))old=old.slice(1,-1);if(!allowed(old))throw new Error('Refusing an unexpected image for '+name);lines[i]=m[1]+JSON.stringify(next)+m[3];found=true;}if(!found)throw new Error('Container image missing '+name);return lines.join('\n');}
export async function updateGitops(root,application,theme){checkedImage(application,applicationRepository);checkedImage(theme,themeRepository);const changes=[];for(const [file,name] of [['api','api'],['worker','worker'],['migration','migrate']]){let path=join(root,'kubernetes/services/savehub',file+'.yaml');try{await readFile(path);}catch(e){if(e.code!=='ENOENT')throw e;path+='.example';}const before=await readFile(path,'utf8'),after=patchImage(before,name,application,old=>old==='SAVEHUB_IMAGE_DIGEST'||old.startsWith('git.radunenu.com/'+applicationRepository+'@sha256:'));if(after!==before)changes.push({path,after});}const path=join(root,'kubernetes/services/keycloak/keycloak.yaml');const before=await readFile(path,'utf8'),after=patchImage(before,'keycloak',theme,old=>old==='quay.io/keycloak/keycloak:26.5.5'||old.startsWith('git.radunenu.com/'+themeRepository+'@sha256:'));if(after!==before)changes.push({path,after});for(const {path,after} of changes)await writeFile(path,after);return changes.map(c=>c.path);}
if(process.argv[1]===fileURLToPath(import.meta.url)){const root=resolve(process.argv[2]??'.'),record=await manifest(applicationRepository,'release',true);if(!record){console.log('No tested SaveHub release has been published yet.');process.exit(0);}const release=releaseImages(record);await manifest(applicationRepository,release.application.split('@')[1]);await manifest(themeRepository,release.theme.split('@')[1]);const changed=await updateGitops(root,release.application,release.theme);console.log(JSON.stringify({commit:release.commit,changed:changed.map(p=>p.replace(root+'/',''))}));if(process.env.GITHUB_OUTPUT)await writeFile(process.env.GITHUB_OUTPUT,`commit=${release.commit}\nchanged=${changed.length>0}\n`,{flag:'a'});}
