{
	"data": "ENC[AES256_GCM,data:WiT+2EX+r+RKqML/CIibqdkwU5GH3H+DelpsrWomSH211nfFCJSxlvi5Bv8siuH77FG6kA8kyYz3Ir3wVN4iGIdBx1//C+BIqgp1EkCoJ66Wfqr/FeM+BXjsLF7P43Bu0EEVopyFiF1Eyd+3kPLdVy/oacS/bIUQk+onThoQ1liWJifdTZP3kHbiO4x9EL2SwZ2gAx8ZbO41LKpTZHg=,iv:X4mIZ3u9tbl2PgaphtDCNviEfPIJOyfoEeb+yvahci8=,tag:3GJXN693gArkcSZtL+Q3Aw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1srnna7u8qckhtp66ulrv8tduxgjc6auxt50jdw4d4fgeu26pggms44wuu8",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTnU4aGQ5UTN4TW9BbUpH\nVndrL2RYT3N6WG90ME5ja1NYY2pMK0x1dHhBCmUrRlFpSTd2YzdLM1hqb24vKzlu\nOEZKTm5zdEwxeVpKM1BPdnZMRk5CZDQKLS0tIHhoeE4yb2NYaWkyazl0R0p0UWJB\ncHFza2VzWGRQTnJMd1psV0VOeFpETFkKYYBeDluG1bJbumDfBNev50DGHUDgK60L\nn974Co2UEQFTw+f/Yj3XnvjYzCxJ23ZRXbzsX3Xo/6K06RvE9WE9Sg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-15T15:35:38Z",
		"mac": "ENC[AES256_GCM,data:XSEl+ua7ffau+nNVDfTyNiBTdh+iRmr/1WNX6Autu7OdciNlGY345anHgjF6lz+XxGNuVrJE/4K7pyG5yxiMRgS/pDsz5l0yPxB6wmW5bfOSut3nITF/3jF+YLJNnBNqN6/oX0xfXhcrWM/OX9ezrz9dttJv9GxAJBI3GSlX8eo=,iv:5xT0nF7YKU7cxno/vFl8Lko3Uxhizw4PJpiM2/HMEJU=,tag:a/kBYP1WAKu6x+1lIdYu4g==,type:str]",
		"version": "3.12.1"
	}
}
