{
	"data": "ENC[AES256_GCM,data:d35gMapk6lRkeOLtMWuZgm/ZXhH1qaHqNbkzJ4PEzSAbt4G8qvYBFl/aSrQguGAbBljxld1srGLwAThO/E1Y6fDDCC3zbm5D2Lq29HxKjsAFCipP1odqk8G/nlKOnMjvskdnbA37ay+g8j8oa7lpKi1l2NYmSv/nzQmPyZNV64JraPVbfJSVmCxBG5S0uEfenQZcycdJ6pB4Ni0PMfg=,iv:X+A3ott/jhFoeSccK08waHWtOd6lpsfXV9zsgFxgv7k=,tag:AIDHLNIbULMYETMKmxHvEQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1srnna7u8qckhtp66ulrv8tduxgjc6auxt50jdw4d4fgeu26pggms44wuu8",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua0J4UnlKT1UwTjB6bVQr\nRWN1UXpkZTR2TGprY1FubmFFZW9BUk1MVTNzClowZHBzWnRvcFJZY0R1d3VOQlds\nWkU1clN5VlQ3K2JDbkplKzM3dUJNZUUKLS0tIHJUeEVSa3NpKy92enJiWlJjbHpi\nRmRySHNSTHpML2VQNjMzS1k2SG82aTgKlf05rknSNbgOIUqBIEzVLJZ60MakJSZL\nRd6dOb3t6H2Buucsw7M/FHuQbUoIG6eIieaQxNPViFzNyagzUWkbtA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-11T09:37:18Z",
		"mac": "ENC[AES256_GCM,data:+A+ym9Mhx+MLA0iqKJv23zeG5mnxHKInTjNpGQ8wlL0eqm6rUatE4wevaAJfpURFE7N/v8yziB43z7mt4CGiT9q+I8FNK1aDmjTkrVx+SDbGfNOEqqCpvvc8Xz4md+iM2ZVsgxVcB1SJfu5PDK6lQKx6COexICYYeXe0WRrDtoA=,iv:lAO41MtIrbuSvMYv2PPCR15ut/+Lq5WV53BZF8iakCk=,tag:jgKpeumpGL0g1YZLIe9phg==,type:str]",
		"version": "3.12.1"
	}
}
