{
	"data": "ENC[AES256_GCM,data:JTSlvUfasv+S5WSyu2EStQEv+xcUBo7ZUGDqQ5cdDSrOYn/oO8Uz3h4hhr0gquZTNjgrfJ02p82cdqf+Hl/m8uwdl2m6owWDEYynwER9tjhUAY963QOZVYcFXCLDCWBJG7Q4oRCuPLQuxbJ1H5/XF0DgfJ+2MXYbZNpBX5ijtmCKsD7h8+GyNTKWjWtZbvz7odK4nnS5jCjiQ7+UUVk=,iv:JpbEfEKubQTdPT88l6a7VWHUPpUv3nzaR6PBFN7r3sA=,tag:yNKNH+jKv7JK0wTyaRp6tg==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1srnna7u8qckhtp66ulrv8tduxgjc6auxt50jdw4d4fgeu26pggms44wuu8",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYnVHUXJadXNyK244V29Y\ndjJHYmorVjBXQkRXNFF2Y0ZYZng4K3VUcnlvCkJZaS9xbjFrZnQ4dm1LSjVqV1VO\nQ2JaUWEzcmJuVEhzaTkyVXYrVFgrY3MKLS0tIGwzNmNYYVE2bTZld1lybHJrZCt0\nRTZTR1NmU1kxL3Bnc3M1bWJCQVQzcmMKQX5mPfhCX4wVDfde7rtDjMSmeL4+SFM4\ntidiXikaNa5s4OriK5Gc9L8L/MB3f/5lLBtuqakbUkjzrQpJ7H7ttg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-12T13:20:36Z",
		"mac": "ENC[AES256_GCM,data:qnuaapEqA5wj3/CmbDHD8XlTN4YvCNqJKlm/u2tw6Y+62JxBGoXvO8RKMXp+ZYCWOH1IpghXki50AQ3hgEGrqCp6p/xBPTi+TEBWiRfJm/lSTzeUuzOUTz6000OJULsOsZ8tq0VfEN9H8KWVQo6GGopATLI5qu0KlnL2ZTQ2SJM=,iv:92xSCKC+VGBPTvdHROXG4z9U4mwYgcE+EbaWwSZ0cYo=,tag:QLtPeFTv/piRb2CuFyFF9A==,type:str]",
		"version": "3.12.1"
	}
}
