apiVersion: v1
kind: ConfigMap
metadata:
  name: tailnet-dns
  namespace: tailnet-dns
data:
  Corefile: |
    infra:53 {
      bind 100.64.0.1
      errors
      health 127.0.0.1:8081
      ready 127.0.0.1:8181
      reload
      hosts {
        100.64.0.1 hl.infra
        ttl 60
      }
    }
