apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: headlamp-cloudflare-api-token
    namespace: headlamp
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:pyg1fvSUDDGkIL/N18gV3JWKupHt4mZtOEFNoFg=,iv:AeRJas7NHZEs80825OYPqbGWbZJezd6BWPobqa7ZhlE=,tag:G3UCUB1R/7WAdzjYTu7RHQ==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:u8BEwz3EElYHQh28I5lFpfoypm3cXycJGw6a2o1AgSYhD8I4lq1KC/HjPpCFNR4WArf+JY8=,iv:HZGyhWKAapvjgIlK+SOOOTG3wzIiZSw1d9Yihb8z6kU=,tag:PK0ovMRkg+N9/WNPoNhqqw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMnZjZUsxNk1ZRURMYnhO
            RVR1NjYvcVRLRVBGeFV6bHRUV0x1bm02eGdzCjFKNzFNQXo5U21kRm0zeVcvWXl3
            eGFCd1VWcmxidVovZGJpM2J5eUdCSnMKLS0tIC9QRnZ3QjAyTVJ0M0UxdDVYMGlN
            aHlUWU5WU3hSVTV4MEFWM3l5RDRpeFUKvfjEztRbNHK7eiQguMh0pCFfsL8v+5SH
            zwjm3GjNHlEfWvp7QKVtLsHXJsGExP2lrYsw6uO7lBgvaZ8uBdF+ZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
    encrypted_suffix: Templates
    lastmodified: "2026-09-25T19:47:01Z"
    mac: ENC[AES256_GCM,data:LbwNbuy5mVT+y5ndNXmkdcD7fmuIkPGKgSj6UyAlT7NPkX0hVkAVggqmTjABciOhPa+EfJDmFJSs+kI4iyJmj4i7TehNLVTLbPOdhWYOzPZAZf3BYTVJq6GLLymDL47UZw3PhfVMfk/K1tGLzV5l1DTprv+RvoiSKHu8gF/sRG8=,iv:I0vMSOQ7T1WigwA56HgJRJps7fLIh3g2To4iptwteXE=,tag:cnT2qR07h39BRRrQpV5a0Q==,type:str]
    version: 3.13.3
