apiVersion: apps/v1
kind: Deployment
metadata:
  name: kronorite
  namespace: legacy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kronorite
  template:
    metadata:
      labels:
        app: kronorite
    spec:
      containers:
        - name: caddy
          image: caddy:2.10.0-alpine@sha256:ae4458638da8e1a91aafffb231c5f8778e964bca650c8a8cb23a7e8ac557aa3c
          args:
            - caddy
            - run
            - --config
            - /etc/caddy/Caddyfile
            - --adapter
            - caddyfile
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/caddy
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: kronorite-caddy
