apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thinkcentre-web
  namespace: external-services
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/enabled: "true"
    gethomepage.dev/external: "true"
    gethomepage.dev/group: Development
    gethomepage.dev/name: Rybbit
    gethomepage.dev/icon: mdi-chart-box-outline
    gethomepage.dev/description: Private web analytics
    gethomepage.dev/weight: "300"
    gethomepage.dev/siteMonitor: http://caddy.rybbit.svc.cluster.local:8080/api/health
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - analytics.radunenu.com
      secretName: analytics-radunenu-com-tls
  rules:
    - host: analytics.radunenu.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thinkcentre-http-gateway
                port:
                  number: 80
