apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: runner-registration
    namespace: ci-runner
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:ZL4E/1zNYFURuVjIycbMSuT1PQ==,iv:f/eas8s05pkNq4YddPW8bSb0K0WiL29XRx87C2XZamk=,tag:z9se9TtH/IByYb65SHmrzQ==,type:str]
          stringData:
            token: ENC[AES256_GCM,data:I0o3rigr6sQLcxDGiP98cOSmMAboe1dJ/3Saax2HGbPEjrCHA321TboK8o7egUSehcF6CzM3i+pytzR2y4oC5A==,iv:jI7vujeQYq+Y3ZTAJ+GKEDMt4T4x7aq7lejYBw/zcI0=,tag:Q7hHWaFjBvGKf+KK/p7HYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFS2gvUE03SlpLc1AxbjJk
            WGFwdGZSQ2pubWhFeTNJaWpKVlVWZGphQlhzClFQTnJZbHllSnI1SFVBRWRFK0xo
            ekJZbHpISUpRUlcyZ0NNUEdUamo3Q2sKLS0tIGRUUERmM2k3OE1MbEZzRE9RcEJG
            azdWM2MxVmkrT1ZwallqUlVyR2xPYzQKpxUrqowJUJp8yQLuAuZA0yCTVy1y8MUb
            u2uFp7tRSndqNL5FObBvnDTZGgdtb+9kiDwxcMQr/KKeDbFb6rC4Iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaTNPQUhjeWZnZFhZUUJX
            cFA3R3dnYjlmbTZ2dEFhVlZOOHNYR2Izb3pJCjBSbnpINFNtcEFXVFFSemU0T281
            REdzU1JxZThEbUZrU08zR2pkOFMwWEEKLS0tIGZBUUd5dENsYk9MNXM3cFg2bUxW
            MGpwa044c3U1dXp4aUU3amtuRG1SZjQKgLPOy61QqFc9g59xR9VD8xewmkBggjwe
            Iye6rHj8ottHq42835Q3uFDwPdoSAd6YZ4OXIBLRDrNNqiZvbPYo6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-10-10T07:07:35Z"
    mac: ENC[AES256_GCM,data:BEh0jTUb81UCOCWK+Sf01zXOQ9ZdfmQFiyv6HsRnoiuFuBvHsxmcxDcNc4y2EvIKUS2YRtbbwvdV7xXmCcxGVQOKYXtMYFrqcWK3tyClsZnxwHLpK/WAaRp2n7PtFy/xG+4NWLXSqdhcDX/hCfVChXmKtr9jftryoDSmqJksfwE=,iv:IdKzuG2kPjA4erEt1bU3Hm7c+pU7UPBXMkNzx6GQFS8=,tag:9qfBMk5VvLVczueTtHCazg==,type:str]
    version: 3.13.3
