{
	"data": "ENC[AES256_GCM,data:sJI0FTJ+fPjpTZe9we/dCIr+SWWiimPTo5K5XVk2yyP0UteCkG4J9bkTwz7w6p29DEE4USG12gKWjtRgwW+81GBKjyzcxTRVrfF5Do8pBW26m4eG67XKGH7RARv8RK93fGW5GRyaPEYQeXayZEwIHRfcaDt27SQL+i5JLOEuJXUXOr83JaBITnNBIVWTOIQWaavfNfnyfvpYc4LxLqU6ZVYhIg==,iv:2p2uQp8IVUn52sd55vvxO/jTCzty4OVKVrhdfZW6c1s=,tag:blGpTJOVGW3zTqm82TsATA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19m937jxq4gfpfw69w3l6606tq8fajlhrt6462q6qxcaucd66l5uqmq4u6n",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUGtwakdYcjZRL0gzYkRX\nYmVSUFVoK2VrUnZaUkRRTG1VTnVOYVZGMG5VClZKZG5kNnp4ZFFnNlRCQjlhQXpa\nTWltZHkzZWdKTFZFL2JnaEhneHQvaUUKLS0tIHppbVEwdkRFU2l6dmpRQ0JQb2hO\nb3FxSzYzcFhUblE0dTl0VEN1cGxLN1kK+p4H8BGanN2sZMPU78qV9Sc7hepGtbIg\nwgAf4LNA1Z8kgyKPodhmThtzYV8OvoROCEKWJYHFKcogAtSBd44VYw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-11T08:25:38Z",
		"mac": "ENC[AES256_GCM,data:DOicmYDx24if+u1o/6F22I5ztCucNZXo5OC2tg9SLuLl/ZQ4QzCz72lw+GWg191L1DvrtlTiwiai8php6yRYpCX7qoWwq5L420Zy5RdFxHPAr1ISKzfMZbbxChmWr511EZuwJnRffjpxECwJh19yxYiRzANiMvWsEXRWGC41M4Y=,iv:+3SPn3qaBqo2Jsz78DRiOjX4n0PZ56ld3R1TtH35Li0=,tag:pVu8UPURlgdHMtGnwUr2+g==,type:str]",
		"version": "3.12.1"
	}
}
