{
	"data": "ENC[AES256_GCM,data:Io81365quCQ0/08TmhlAO7dqp7OLMNW6nDkI3rAi3U0EUkjM3ZyG2yR/C57BBH5ingU9YU58WtqlmzeAEd8YnwqojlRAGEQLI3EindmAZXewzvHr6ormZ7XtaKDrsfggFxwz54ePxmCJz/BE/KSq0eSKslqs/cw2M5i3fd4KP1r1SRo1ybIHESk48QaK0Iy7KlpfkvNfNqpN4ikx9a2bCS6BmQ==,iv:1Zz+ML3U/Dk+jlm6czxyS3+3+H3ufqJb+9Yqiu7qXYo=,tag:y71AgHpWVHMcaTyr+j7a9w==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19m937jxq4gfpfw69w3l6606tq8fajlhrt6462q6qxcaucd66l5uqmq4u6n",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTVJVT0kwMy9ZMUVUVHRs\naE00NUovV09HNGpsZC9vaCtVODRvUU1MYWdFCkF6T3pmUFZvZktHTkVOQnJaL3Ry\nd0hOcWhmMFQvNGttUHMwbGptRTUwekkKLS0tIEZYYUMvM3JaMmtXR1VqeU1ZRDl4\nT2h2bUl3dVV1NmpnNUN0WkZlWHBpZUkKHrIWTZPcTf+RO0vl5nJzq+l2+448PAyB\nw/cdPoRl46DeNT+Pa80OhBihmwK5SAXyXMPbI1x4OkQPBLLRGliZoA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-07T19:16:48Z",
		"mac": "ENC[AES256_GCM,data:wkRz9+6hnquG6IboVCPh/M8fcC3AhGEhxLIFJb1mcIQUJQdbs8wrXPDdB0ZJRnIZwzuqZWlPowGz2QRBa/r8FsITfIxTci0nv5/l5qOoihcDMqzc7sxxGNPE7F0x/cgJgoH+g3YWlruBQ0zzJ8KMC6tYAUN2Ic3S/XpZkmLzmIk=,iv:E5VIUIT+h1dVBEIBajekBDuSE3Ee0wVIOtlcKRLyBuM=,tag:AMjTS3Opq5f1urIV5rsZEg==,type:str]",
		"version": "3.12.1"
	}
}
