{
	"data": "ENC[AES256_GCM,data:+vy12u9E3I9stgIAd3cy60OCxNGabJhr+WXJDFckCfTqw9VeSyJexaxqyUkth46el2IxnPJYvHX3emNhWsF0W4UbILf0H+EARNavQQVumihaOlG5k7gggYJR6Q5Trfq4/sS9Xy0vDU6UBi7REsjcrQAuMG4f+9q4rXnixvEqU1tswfX+KsWZlOki2sdgd3eq+kZ+ZNmFYw80t3bvSGb3cLRO2w==,iv:sOCAmuNbGkNjDBN2Dubj1scP5FoJ0sCCaRUZifiu3kM=,tag:owMUG3ElfbNx8QWruQYB3Q==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age19m937jxq4gfpfw69w3l6606tq8fajlhrt6462q6qxcaucd66l5uqmq4u6n",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SGNDZUJEYUxneCtwSjZ6\ncEFOQUN4QnREY08vd05sQmlhWVE3d3NMc1g4ClphajlXRFBid2dDS0dRTFg0RXVQ\nTmdUYngrQ21La1FxS1dka2N1Sm1ibTQKLS0tIERLTnZWQ0JiUE0zUWJ5YnkrYU9T\ndWh6TkxpaVM3YmJmUHZpUWtKbXFsSEUKfxj15/SZEFSSi0rkLFbpNZJqklyuIqoj\n6B8kOeBdj3qvjxbGRphhNLfMd2wTlaUX7AJlIt+cK1bml7PeyzIvYw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-03-14T11:44:08Z",
		"mac": "ENC[AES256_GCM,data:jF7ZY2UyIob/2bzNnuBwxMlA5/+T6aoxrg6hggbhuJ4MlrL4HyEbNaIcyMigQ1QkE0jir0XV3TKAOwnXfXr3yx2VfbFc/L/LdJtK7keSwHNZTMhn9L32kA9FZwoni1SQUt594DUo9GQJ/P0S76v8gu+8f9jAVL3xac6TUV8bsLM=,iv:3tGO69nYLDgXJ4rNBoo2wcyHXWUoXBWhpDwt0aOk73k=,tag:yP7pHtrBXy4ow3tpriE2Jw==,type:str]",
		"version": "3.12.1"
	}
}
