services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    network_mode: tunnel_net
    restart: unless-stopped
    environment:
      DOMAIN: "${DOMAIN}"
    volumes:
      - ${VAULTWARDEN_ROOT}:/data/
#    ports:
#      - "8000:80"

  ratholec:
    image: rapiz1/rathole:latest
    container_name: ratholec-vaultwarden
    user: "0:0"
    restart: unless-stopped
    network_mode: tunnel_net
    volumes:
      - ./rathole.toml:/etc/rathole.toml:ro
    command: /etc/rathole.toml
    working_dir: /app
