apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager
    namespace: monitoring
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:37ZZFRbFh5dIr1cc,iv:ldlR4Lbuv3d1yRAsxRE+IgDhL+J03fLX1o5sM1WnpLM=,tag:5QlEpzzfAPrN0l2Yvmpp3Q==,type:str]
          stringData:
            healthchecks_url: ENC[AES256_GCM,data:Ik8XWjsV4pXeaXaito6meXauw+cS249TWurOEYkOOwYkalkVH/DKDxPFEnYQTJgrnVOLyRyMQvI=,iv:OIAOKYoNYXDX++k04xM/oNjxUjsVUoXQ4BQ0gAtqBVY=,tag:QwwFHJMDPilbdNTsRH+Byw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVllnUHIrbXo1Q1dVcTF0
            akdWaTUwN1JCK0I0VGdIQ2djcS85R3A1NFV3CklOaXdRaU5KWjlTS2tBajBOWTFO
            ektuOXJMNnRGNVV4OXQ5WWlFYm9xTWMKLS0tIG1xbnhzMGl0ZW9rVk9Ddm5QK0xt
            eFRyTFNrdmVueC9xZmY4MDJaRmxyaVUKaqlQqtcFNR1qTmo2Kb5O62TkWdjk0yg0
            fXJaO5hhyeAmWNF/yT2CLsMFP5SvVVeNGfFXaaf/Awj0m0/FstfWmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d2NLZkNoay9uTUZBbWxt
            TmxXWHVCbEljTVJKWUxkSmR3eVhiVUlCaHk0CnNNQzdxb0QwL29OdnR3WnpPNUd2
            ZnB2dDlXOE5PdU0rcDM3UVlnSGpNQTgKLS0tIGZNSUNJNktSOFFhSnRhWGJXVWlS
            TWZQODFsaG1tVGx0MEVhT0diWDB5ODAKj9AWanN3ZZs3ZbUYLPg728QUihKfF9hN
            obK8y3c7iW1IIh0ZhShGs3TrlucjXCOqEYI9604a1FSdMtZXLC1wOw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a4pmutcnee2nflw6t70lt4cq3u08sp5d60andp5hm7wmu9hwsp6qlcp659
    encrypted_suffix: Templates
    lastmodified: "2026-10-02T07:56:05Z"
    mac: ENC[AES256_GCM,data:drOjJGoOYmu/dxTENQjbnL4zocnwJYIJwNpwTmQXfgMyYiRkfOV4vvtYP/X9uP6rnxDYIyBI+zPvXCH7MBL1xBkgdR02UM0hpdGYKq9t9ouZV7KR8JNmduzguF7AfSluhZRCm2gLKZWMpySbrcVIFOIW843l6lRhUP6gLpfnWDM=,iv:/QNFSfix5RBUZI5lXSXTsehLw950miAY8bZp97XnHYQ=,tag:nlHmM2Zqe2ZUm36Bltbeng==,type:str]
    version: 3.13.3
