apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: grafana-auth
    namespace: monitoring
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:ixs5otSqiSV0t5au,iv:5xEvCf3e381GgMXB53wnozPDzeLf6DmoTlzMwLZSE60=,tag:u6E1ssfEE3QkgCw9A1U/Bw==,type:str]
          stringData:
            GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:ISy2p1F6Iso1Qw==,iv:NSV1Z/xlmYa6GTRxM9pBhifP0c++gEDTaPzn9nzDG7Q=,tag:lJalNQcErEIlmxxcwnSnnA==,type:str]
            GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:/Hx0xBV6Sw/5Fol0mvIzXbW28/G/cxluqcjdxNp723RA91Qi+9R21lX+I5o2zGL2SZrUxvwG7j5GxdhgIdPFKA==,iv:cFvVzei+9PHKqZOkR6X7TaRs23ZO37jNmPF59Qwmfd4=,tag:liCTapbjs8l09RghNeGmlA==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:1bv99Kvolg==,iv:A34evIv8yxWetvj5q0huqn0cpooRvpvBGcPuCGWV4So=,tag:Wxc3cpvA9+qiikQOYUkXkQ==,type:str]
            GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Fqi/uOEkGBrSjvwjsUrntf0Tyj7NWNhust6M4APecr4=,iv:ItCwfoXSy2bGdzAQ8t5hQ/gEH1cW74nmOkdUWlAbVqs=,tag:5uBc8mr2n/+EaAqhRA083w==,type:str]
            GF_AUTH_GENERIC_OAUTH_SCOPES: ENC[AES256_GCM,data:JZwKr9urXK5QfwwwJ2fPL88U+pGZL8KCxhc=,iv:oM/jdomLiWEd75NHKYGMWymV9zG+/LmAG5EokO9uXcw=,tag:c9Ckn7G2iKgII3FBFyTQmA==,type:str]
            GF_AUTH_GENERIC_OAUTH_AUTH_URL: ENC[AES256_GCM,data:sLmQiwNXQgqn6ftU2QiEm3Di7TED1KQ5b3MQPWcY+RfmwtwLpeJMCQmu9uni/LRqmNoapLQYq/CzZYcOB7dgS2TxWQ==,iv:esU31npK7cePolGbLf6THSJ+76wT8AxP8MtmLNP2+NY=,tag:i7r/+ZzpvxKdeSgom+rpjA==,type:str]
            GF_AUTH_GENERIC_OAUTH_TOKEN_URL: ENC[AES256_GCM,data:lX44FXst4vHvLH/scFqNT3ex9irGFUH1rb6keXAdXZ8BIfF99NNivsoL0uMrdbpVirvE1E/aBBSoBuUpFdDoqjF69LA=,iv:zrrcKghhlyAVFlNwTtR/KnZORMM2GU95v81/KDWECCc=,tag:wJdJWGYPfMnumqUwbDsiow==,type:str]
            GF_AUTH_GENERIC_OAUTH_API_URL: ENC[AES256_GCM,data:WV3rz9YBKSwCRjK58HztRX1kqg/8OFkhw92Sh20tPnzevwNCEROC1e7WvINVb+Zq5VtjhFBBGWkniLSUNHlWIcxEZnlpQ3g=,iv:yn/I1d/I1jl8VAHEnpf3Ox8Llhiy2dxUdvkzksfpXiA=,tag:4rrZbyPmSY+uLbj/J4OphA==,type:str]
            GF_AUTH_GENERIC_OAUTH_USE_PKCE: ENC[AES256_GCM,data:mLvcAA==,iv:u46jOpSgoxhdXV8GiAkC4emzS1/g1xvxs4K/bVZp0ho=,tag:VApAvy7I2oV9zi3gY0mySw==,type:str]
            GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: ENC[AES256_GCM,data:d3PIdSmV9Q/1WMoF4y0JOwV6,iv:Z/6UjkPUOrDNshRaJL64AK2qrHS/GVT2wLpcLEmJgOk=,tag:x4ULFhVI4vm8JYvAC9Cf7g==,type:str]
            GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: ENC[AES256_GCM,data:wHbke9sfvVu4,iv:nzd226tCTOIA1uwY09X/Gq595enTc7yz4fc0vUk6JKg=,tag:/CMXoD8yaFrYuRKdze0UuQ==,type:str]
            GF_AUTH_GENERIC_OAUTH_EMAIL_ATTRIBUTE_PATH: ENC[AES256_GCM,data:sYjbGY4=,iv:piV3nUXjsfxP8KMR7QpoY8zBkH4RUcxJmPHJwA7mXOc=,tag:URr4hrapa1FHZ7xQpa34og==,type:str]
            GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: ENC[AES256_GCM,data:2LCcU2YTLU7gBYHcJcFNOCZwYBVlSytQeMpsWqENZxtICtz1CH+YIdMdjHi3P0YY11Qn0T26urz9pRE4gYCCxQkJFXqtQwzFIwCp6+bO6XguCDK4LkDmPtbEYfkJOuL9AvM2IQpJVAAFgkWmfr4Fwh9oUnuf8knKw0O8gC7INJKQ2whdPREAmg==,iv:YVdbX/XO/Ndi8KC/AW2bmGS0GVlv+eu8zGQwxfpLgXk=,tag:0aaPR/JsHbpb8wcZ1l5Mvw==,type:str]
sops:
    age:
        - recipient: age1qwuleu9k2gzgex43tyhhy80vgg9kym5dcdne32x4f0lw4xzsxy3spau58l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTElyL254eWtJOTdzRjNT
            Wi9ZMGxjdmlmMXVwMCtCb2QrVE1sM3g4Z1JzClk0UmFNdmlHbFNpVUNWOFcxSXhr
            OC81a2FXOWRwcDJuVmZ3WHkvWXRZNmcKLS0tIEthVlF3cUZrRzNuYmRCQldkUU9T
            VVlUUjNLS2dTTUV4ck1QNnBtdEd4UzgKRESnmf7mXG7nLeJglFkVRrcJqTQnhB1R
            JpIRMxKJKvrCbbrnGNCAvAoBBUzoiCEMe3HK8m9co/0MIwAfNN7gTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-20T12:49:45Z"
    mac: ENC[AES256_GCM,data:yuXWh7XKzu1K6I1Q/Qs0WAgn6NCUK/12+VfLvcCDkLTbICdOza20bqxzu703lWVchiwNB5LTgqJtHWxXkt9ztlaJp1HLVkxjtEScUf/4i4K0oR1w0LqB9Yo8rs0LztBSocKE/JNx9cW/KT+ERIThmKHoDCTR44pieIpdm7nMjnU=,iv:nZSyisHahWDCJyYDG4BKTaeUPqSD3c9ZVp09l/NWs5Q=,tag:3U/vvgSGvutzU6QIdtWsZg==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
